import { Song } from "@/utils/types";

export const songs: Song[] = [
  {
    name: "500 Miles.mp3",
    path: "/audio/500%20Miles.mp3",
    singer: "500 Miles.mp3",
    title: "500 Miles.mp3",
    duration: 0,
  },
  {
    name: "A Thousand Years.mp3",
    path: "/audio/A%20Thousand%20Years.mp3",
    singer: "A Thousand Years.mp3",
    title: "A Thousand Years.mp3",
    duration: 0,
  },
  {
    name: "AKU TAK BIASA.mp3",
    path: "/audio/AKU%20TAK%20BIASA.mp3",
    singer: "AKU TAK BIASA.mp3",
    title: "AKU TAK BIASA.mp3",
    duration: 0,
  },
  {
    name: "ATAS NAMA CINTA.mp3",
    path: "/audio/ATAS%20NAMA%20CINTA.mp3",
    singer: "ATAS NAMA CINTA.mp3",
    title: "ATAS NAMA CINTA.mp3",
    duration: 0,
  },
  {
    name: "AUDY - MENANGIS SEMALAM.mp3",
    path: "/audio/AUDY%20-%20MENANGIS%20SEMALAM.mp3",
    singer: "AUDY",
    title: "MENANGIS SEMALAM",
    duration: 0,
  },
  {
    name: "AVRILL~4.MP3",
    path: "/audio/AVRILL~4.MP3",
    singer: "AVRILL~4.MP3",
    title: "AVRILL~4.MP3",
    duration: 0,
  },
  {
    name: "AYAT-AYAT CINTA.mp3",
    path: "/audio/AYAT-AYAT%20CINTA.mp3",
    singer: "AYAT-AYAT CINTA.mp3",
    title: "AYAT-AYAT CINTA.mp3",
    duration: 0,
  },
  {
    name: "Adele - Easy On Me (Official Video) (320 kbps).mp3",
    path: "/audio/Adele%20-%20Easy%20On%20Me%20(Official%20Video)%20(320%20kbps).mp3",
    singer: "Adele",
    title: "Easy On Me (Official Video) (320 kbps)",
    duration: 0,
  },
  {
    name: "Afgan - Jodoh Pasti Bertemu(Naufal Cover).mp3",
    path: "/audio/Afgan%20-%20Jodoh%20Pasti%20Bertemu(Naufal%20Cover).mp3",
    singer: "Afgan",
    title: "Jodoh Pasti Bertemu(Naufal Cover)",
    duration: 0,
  },
  {
    name: "Akhirnya Ku Menemukanmu.mp3",
    path: "/audio/Akhirnya%20Ku%20Menemukanmu.mp3",
    singer: "Akhirnya Ku Menemukanmu.mp3",
    title: "Akhirnya Ku Menemukanmu.mp3",
    duration: 0,
  },
  {
    name: "Alan Walker - Alone.mp3",
    path: "/audio/Alan%20Walker%20-%20Alone.mp3",
    singer: "Alan Walker",
    title: "Alone",
    duration: 0,
  },
  {
    name: "Alan Walker - Faded [pleer.com].mp3",
    path: "/audio/Alan%20Walker%20-%20Faded%20%5Bpleer.com%5D.mp3",
    singer: "Alan Walker",
    title: "Faded [pleer.com]",
    duration: 0,
  },
  {
    name: "Alessia Cara  Im Yours Official Audio [Mp3Convert.Tube].mp3",
    path: "/audio/Alessia%20Cara%20%20Im%20Yours%20Official%20Audio%20%5BMp3Convert.Tube%5D.mp3",
    singer: "Alessia Cara  Im Yours Official Audio [Mp3Convert.Tube].mp3",
    title: "Alessia Cara  Im Yours Official Audio [Mp3Convert.Tube].mp3",
    duration: 0,
  },
  {
    name: "Alessia Cara - How Far I'll Go (Official Video).mp3",
    path: "/audio/Alessia%20Cara%20-%20How%20Far%20I'll%20Go%20(Official%20Video).mp3",
    singer: "Alessia Cara",
    title: "How Far I'll Go (Official Video)",
    duration: 0,
  },
  {
    name: "Alessia Cara - Scars To Your Beautiful.mp3",
    path: "/audio/Alessia%20Cara%20-%20Scars%20To%20Your%20Beautiful.mp3",
    singer: "Alessia Cara",
    title: "Scars To Your Beautiful",
    duration: 0,
  },
  {
    name: "Am I Wrong-Nico ft. Vinz.mp3",
    path: "/audio/Am%20I%20Wrong-Nico%20ft.%20Vinz.mp3",
    singer: "Am I Wrong-Nico ft. Vinz.mp3",
    title: "Am I Wrong-Nico ft. Vinz.mp3",
    duration: 0,
  },
  {
    name: "And I Love You.mp3",
    path: "/audio/And%20I%20Love%20You.mp3",
    singer: "And I Love You.mp3",
    title: "And I Love You.mp3",
    duration: 0,
  },
  {
    name: "Ariana Grande, John Legend - Beauty and the Beast (Lyrics).mp3",
    path: "/audio/Ariana%20Grande%2C%20John%20Legend%20-%20Beauty%20and%20the%20Beast%20(Lyrics).mp3",
    singer: "Ariana Grande, John Legend",
    title: "Beauty and the Beast (Lyrics)",
    duration: 0,
  },
  {
    name: "Arms.mp3",
    path: "/audio/Arms.mp3",
    singer: "Arms.mp3",
    title: "Arms.mp3",
    duration: 0,
  },
  {
    name: "Avenged Sevenfold - Warmness On The Soul.mp3",
    path: "/audio/Avenged%20Sevenfold%20-%20Warmness%20On%20The%20Soul.mp3",
    singer: "Avenged Sevenfold",
    title: "Warmness On The Soul",
    duration: 0,
  },
  {
    name: "Avenged_Sevenfold_Afterlife.mp3",
    path: "/audio/Avenged_Sevenfold_Afterlife.mp3",
    singer: "Avenged_Sevenfold_Afterlife.mp3",
    title: "Avenged_Sevenfold_Afterlife.mp3",
    duration: 0,
  },
  {
    name: "Avenged_Sevenfold_MIA.mp3",
    path: "/audio/Avenged_Sevenfold_MIA.mp3",
    singer: "Avenged_Sevenfold_MIA.mp3",
    title: "Avenged_Sevenfold_MIA.mp3",
    duration: 0,
  },
  {
    name: "Avenged_Sevenfold_Until_The_End.mp3",
    path: "/audio/Avenged_Sevenfold_Until_The_End.mp3",
    singer: "Avenged_Sevenfold_Until_The_End.mp3",
    title: "Avenged_Sevenfold_Until_The_End.mp3",
    duration: 0,
  },
  {
    name: "Avril Lavigne - Don’t Tell Me.mp3",
    path: "/audio/Avril%20Lavigne%20-%20Don%E2%80%99t%20Tell%20Me.mp3",
    singer: "Avril Lavigne",
    title: "Don’t Tell Me",
    duration: 0,
  },
  {
    name: "Avril Lavigne - Girlfriend (1).mp3",
    path: "/audio/Avril%20Lavigne%20-%20Girlfriend%20(1).mp3",
    singer: "Avril Lavigne",
    title: "Girlfriend (1)",
    duration: 0,
  },
  {
    name: "Avril Lavigne - I'm With You (Album Version).mp3",
    path: "/audio/Avril%20Lavigne%20-%20I'm%20With%20You%20(Album%20Version).mp3",
    singer: "Avril Lavigne",
    title: "I'm With You (Album Version)",
    duration: 0,
  },
  {
    name: "Avril Lavigne - My Happy Ending (live acoustic).mp3",
    path: "/audio/Avril%20Lavigne%20-%20My%20Happy%20Ending%20(live%20acoustic).mp3",
    singer: "Avril Lavigne",
    title: "My Happy Ending (live acoustic)",
    duration: 0,
  },
  {
    name: "Avril Lavigne - Rock ’n’ Roll.mp3",
    path: "/audio/Avril%20Lavigne%20-%20Rock%20%E2%80%99n%E2%80%99%20Roll.mp3",
    singer: "Avril Lavigne",
    title: "Rock ’n’ Roll",
    duration: 0,
  },
  {
    name: "BALADA PENGANGGURAN.mp3",
    path: "/audio/BALADA%20PENGANGGURAN.mp3",
    singer: "BALADA PENGANGGURAN.mp3",
    title: "BALADA PENGANGGURAN.mp3",
    duration: 0,
  },
  {
    name: "BERSAMAMU.mp3",
    path: "/audio/BERSAMAMU.mp3",
    singer: "BERSAMAMU.mp3",
    title: "BERSAMAMU.mp3",
    duration: 0,
  },
  {
    name: "BUKAN CINTA BIASA.mp3",
    path: "/audio/BUKAN%20CINTA%20BIASA.mp3",
    singer: "BUKAN CINTA BIASA.mp3",
    title: "BUKAN CINTA BIASA.mp3",
    duration: 0,
  },
  {
    name: "BUKAN DIA TAPI AKU.mp3",
    path: "/audio/BUKAN%20DIA%20TAPI%20AKU.mp3",
    singer: "BUKAN DIA TAPI AKU.mp3",
    title: "BUKAN DIA TAPI AKU.mp3",
    duration: 0,
  },
  {
    name: "BUKAN RAYUAN GOMBAL.mp3",
    path: "/audio/BUKAN%20RAYUAN%20GOMBAL.mp3",
    singer: "BUKAN RAYUAN GOMBAL.mp3",
    title: "BUKAN RAYUAN GOMBAL.mp3",
    duration: 0,
  },
  {
    name: "Back To December.mp3",
    path: "/audio/Back%20To%20December.mp3",
    singer: "Back To December.mp3",
    title: "Back To December.mp3",
    duration: 0,
  },
  {
    name: "Bad Girl (feat. Marilyn Manson).mp3",
    path: "/audio/Bad%20Girl%20(feat.%20Marilyn%20Manson).mp3",
    singer: "Bad Girl (feat. Marilyn Manson).mp3",
    title: "Bad Girl (feat. Marilyn Manson).mp3",
    duration: 0,
  },
  {
    name: "Bang Bang Bang.mp3",
    path: "/audio/Bang%20Bang%20Bang.mp3",
    singer: "Bang Bang Bang.mp3",
    title: "Bang Bang Bang.mp3",
    duration: 0,
  },
  {
    name: "Beautiful Piano Music Relaxing Music Romantic Music Sleep Music Study Music ★132.mp3",
    path: "/audio/Beautiful%20Piano%20Music%20Relaxing%20Music%20Romantic%20Music%20Sleep%20Music%20Study%20Music%20%E2%98%85132.mp3",
    singer:
      "Beautiful Piano Music Relaxing Music Romantic Music Sleep Music Study Music ★132.mp3",
    title:
      "Beautiful Piano Music Relaxing Music Romantic Music Sleep Music Study Music ★132.mp3",
    duration: 0,
  },
  {
    name: "Before The Next Teardrop Falls.mp3",
    path: "/audio/Before%20The%20Next%20Teardrop%20Falls.mp3",
    singer: "Before The Next Teardrop Falls.mp3",
    title: "Before The Next Teardrop Falls.mp3",
    duration: 0,
  },
  {
    name: "Berita Kepada Kawan.mp3",
    path: "/audio/Berita%20Kepada%20Kawan.mp3",
    singer: "Berita Kepada Kawan.mp3",
    title: "Berita Kepada Kawan.mp3",
    duration: 0,
  },
  {
    name: "Betharia Sonata - Hati Yang Luka.mp3",
    path: "/audio/Betharia%20Sonata%20-%20Hati%20Yang%20Luka.mp3",
    singer: "Betharia Sonata",
    title: "Hati Yang Luka",
    duration: 0,
  },
  {
    name: "Betharia Sonatha - Kau Tercipta Untukku.mp3",
    path: "/audio/Betharia%20Sonatha%20-%20Kau%20Tercipta%20Untukku.mp3",
    singer: "Betharia Sonatha",
    title: "Kau Tercipta Untukku",
    duration: 0,
  },
  {
    name: "Bettaria -.mp3",
    path: "/audio/Bettaria%20-.mp3",
    singer: "Bettaria -.mp3",
    title: "Bettaria -.mp3",
    duration: 0,
  },
  {
    name: "Beyoncé - ALREADY.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20ALREADY.mp3",
    singer: "Beyoncé",
    title: "ALREADY",
    duration: 0,
  },
  {
    name: "Beyoncé - Amor Gitano ft. Alejandro Fernandez.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Amor%20Gitano%20ft.%20Alejandro%20Fernandez.mp3",
    singer: "Beyoncé",
    title: "Amor Gitano ft. Alejandro Fernandez",
    duration: 0,
  },
  {
    name: "Beyoncé - BIGGER.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20BIGGER.mp3",
    singer: "Beyoncé",
    title: "BIGGER",
    duration: 0,
  },
  {
    name: "Beyoncé - Crazy In Love (50 оттенков серого).mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Crazy%20In%20Love%20(50%20%D0%BE%D1%82%D1%82%D0%B5%D0%BD%D0%BA%D0%BE%D0%B2%20%D1%81%D0%B5%D1%80%D0%BE%D0%B3%D0%BE).mp3",
    singer: "Beyoncé",
    title: "Crazy In Love (50 оттенков серого)",
    duration: 0,
  },
  {
    name: "Beyoncé - Crazy in Love (feat. Jay-Z).mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Crazy%20in%20Love%20(feat.%20Jay-Z).mp3",
    singer: "Beyoncé",
    title: "Crazy in Love (feat. Jay-Z)",
    duration: 0,
  },
  {
    name: "Beyoncé - Drunk In Love (feat. Jay Z).mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Drunk%20In%20Love%20(feat.%20Jay%20Z).mp3",
    singer: "Beyoncé",
    title: "Drunk In Love (feat. Jay Z)",
    duration: 0,
  },
  {
    name: "Beyoncé - FIND YOUR WAY BACK.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20FIND%20YOUR%20WAY%20BACK.mp3",
    singer: "Beyoncé",
    title: "FIND YOUR WAY BACK",
    duration: 0,
  },
  {
    name: "Beyoncé - Ghost_Haunted (ost Fifty Shades of Grey) (50  оттенков).mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Ghost_Haunted%20(ost%20Fifty%20Shades%20of%20Grey)%20(50%20%20%D0%BE%D1%82%D1%82%D0%B5%D0%BD%D0%BA%D0%BE%D0%B2).mp3",
    singer: "Beyoncé",
    title: "Ghost_Haunted (ost Fifty Shades of Grey) (50  оттенков)",
    duration: 0,
  },
  {
    name: "Beyoncé - Halo.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Halo.mp3",
    singer: "Beyoncé",
    title: "Halo",
    duration: 0,
  },
  {
    name: "Beyoncé - If I Were A Boy.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20If%20I%20Were%20A%20Boy.mp3",
    singer: "Beyoncé",
    title: "If I Were A Boy",
    duration: 0,
  },
  {
    name: "Beyoncé - Irreplaceable.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Irreplaceable.mp3",
    singer: "Beyoncé",
    title: "Irreplaceable",
    duration: 0,
  },
  {
    name: "Beyoncé - MOOD 4 EVA.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20MOOD%204%20EVA.mp3",
    singer: "Beyoncé",
    title: "MOOD 4 EVA",
    duration: 0,
  },
  {
    name: "Beyoncé - NILE.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20NILE.mp3",
    singer: "Beyoncé",
    title: "NILE",
    duration: 0,
  },
  {
    name: "Beyoncé - Naughty Girl.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Naughty%20Girl.mp3",
    singer: "Beyoncé",
    title: "Naughty Girl",
    duration: 0,
  },
  {
    name: "Beyoncé - Single Ladies (Put A Ring On I.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Single%20Ladies%20(Put%20A%20Ring%20On%20I.mp3",
    singer: "Beyoncé",
    title: "Single Ladies (Put A Ring On I",
    duration: 0,
  },
  {
    name: "Beyoncé - Spirit.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Spirit.mp3",
    singer: "Beyoncé",
    title: "Spirit",
    duration: 0,
  },
  {
    name: "Beyoncé - Survivor.mp3",
    path: "/audio/Beyonc%C3%A9%20-%20Survivor.mp3",
    singer: "Beyoncé",
    title: "Survivor",
    duration: 0,
  },
  {
    name: "Bintang Kehidupan.mp3",
    path: "/audio/Bintang%20Kehidupan.mp3",
    singer: "Bintang Kehidupan.mp3",
    title: "Bintang Kehidupan.mp3",
    duration: 0,
  },
  {
    name: "BonJovi-Always (DJ Crimp Remix).mp3",
    path: "/audio/BonJovi-Always%20(DJ%20Crimp%20Remix).mp3",
    singer: "BonJovi-Always (DJ Crimp Remix).mp3",
    title: "BonJovi-Always (DJ Crimp Remix).mp3",
    duration: 0,
  },
  {
    name: "Brian McKnight - Back At One.mp3",
    path: "/audio/Brian%20McKnight%20-%20Back%20At%20One.mp3",
    singer: "Brian McKnight",
    title: "Back At One",
    duration: 0,
  },
  {
    name: "Brian McKnight - Can You Stop The Rain.mp3",
    path: "/audio/Brian%20McKnight%20-%20Can%20You%20Stop%20The%20Rain.mp3",
    singer: "Brian McKnight",
    title: "Can You Stop The Rain",
    duration: 0,
  },
  {
    name: "Brian McKnight - Careless Whisper (feat. Kenny G).mp3",
    path: "/audio/Brian%20McKnight%20-%20Careless%20Whisper%20(feat.%20Kenny%20G).mp3",
    singer: "Brian McKnight",
    title: "Careless Whisper (feat. Kenny G)",
    duration: 0,
  },
  {
    name: "Brian McKnight - Color of the Night.mp3",
    path: "/audio/Brian%20McKnight%20-%20Color%20of%20the%20Night.mp3",
    singer: "Brian McKnight",
    title: "Color of the Night",
    duration: 0,
  },
  {
    name: "Brian McKnight - For You (From _Superhero_) (2001).mp3",
    path: "/audio/Brian%20McKnight%20-%20For%20You%20(From%20_Superhero_)%20(2001).mp3",
    singer: "Brian McKnight",
    title: "For You (From _Superhero_) (2001)",
    duration: 0,
  },
  {
    name: "Brian McKnight - More Than Wonderful (live).mp3",
    path: "/audio/Brian%20McKnight%20-%20More%20Than%20Wonderful%20(live).mp3",
    singer: "Brian McKnight",
    title: "More Than Wonderful (live)",
    duration: 0,
  },
  {
    name: "Brian McKnight - Never Felt This Way.mp3",
    path: "/audio/Brian%20McKnight%20-%20Never%20Felt%20This%20Way.mp3",
    singer: "Brian McKnight",
    title: "Never Felt This Way",
    duration: 0,
  },
  {
    name: "Brian McKnight - Sweeter.mp3",
    path: "/audio/Brian%20McKnight%20-%20Sweeter.mp3",
    singer: "Brian McKnight",
    title: "Sweeter",
    duration: 0,
  },
  {
    name: "Brian McKnight - Win (1).mp3",
    path: "/audio/Brian%20McKnight%20-%20Win%20(1).mp3",
    singer: "Brian McKnight",
    title: "Win (1)",
    duration: 0,
  },
  {
    name: "Brian McKnight - Win.mp3",
    path: "/audio/Brian%20McKnight%20-%20Win.mp3",
    singer: "Brian McKnight",
    title: "Win",
    duration: 0,
  },
  {
    name: "Brian McKnight Jr. - Marry Your Daughter.mp3",
    path: "/audio/Brian%20McKnight%20Jr.%20-%20Marry%20Your%20Daughter.mp3",
    singer: "Brian McKnight Jr.",
    title: "Marry Your Daughter",
    duration: 0,
  },
  {
    name: "Brian McKnight feat. Claude McKnight & Tim Miner - The First Noel.mp3",
    path: "/audio/Brian%20McKnight%20feat.%20Claude%20McKnight%20%26%20Tim%20Miner%20-%20The%20First%20Noel.mp3",
    singer: "Brian McKnight feat. Claude McKnight & Tim Miner",
    title: "The First Noel",
    duration: 0,
  },
  {
    name: "Bright Eyes .mp3",
    path: "/audio/Bright%20Eyes%20.mp3",
    singer: "Bright Eyes .mp3",
    title: "Bright Eyes .mp3",
    duration: 0,
  },
  {
    name: "Bruno Mars - 24K Magic.mp3",
    path: "/audio/Bruno%20Mars%20-%2024K%20Magic.mp3",
    singer: "Bruno Mars",
    title: "24K Magic",
    duration: 0,
  },
  {
    name: "Bruno Mars - Count On Me.mp3",
    path: "/audio/Bruno%20Mars%20-%20Count%20On%20Me.mp3",
    singer: "Bruno Mars",
    title: "Count On Me",
    duration: 0,
  },
  {
    name: "Bruno Mars - Grenade .mp3",
    path: "/audio/Bruno%20Mars%20-%20Grenade%20.mp3",
    singer: "Bruno Mars",
    title: "Grenade ",
    duration: 0,
  },
  {
    name: "Bruno Mars - Grenade.mp3",
    path: "/audio/Bruno%20Mars%20-%20Grenade.mp3",
    singer: "Bruno Mars",
    title: "Grenade",
    duration: 0,
  },
  {
    name: "Bruno Mars - Just the Way You Are.mp3",
    path: "/audio/Bruno%20Mars%20-%20Just%20the%20Way%20You%20Are.mp3",
    singer: "Bruno Mars",
    title: "Just the Way You Are",
    duration: 0,
  },
  {
    name: "Bruno Mars - Locked Out Of Heaven.mp3",
    path: "/audio/Bruno%20Mars%20-%20Locked%20Out%20Of%20Heaven.mp3",
    singer: "Bruno Mars",
    title: "Locked Out Of Heaven",
    duration: 0,
  },
  {
    name: "Bruno Mars - Talking To The Moon.mp3",
    path: "/audio/Bruno%20Mars%20-%20Talking%20To%20The%20Moon.mp3",
    singer: "Bruno Mars",
    title: "Talking To The Moon",
    duration: 0,
  },
  {
    name: "Bruno Mars - That's What I Like.mp3",
    path: "/audio/Bruno%20Mars%20-%20That's%20What%20I%20Like.mp3",
    singer: "Bruno Mars",
    title: "That's What I Like",
    duration: 0,
  },
  {
    name: "Bruno Mars - The Lazy Song.mp3",
    path: "/audio/Bruno%20Mars%20-%20The%20Lazy%20Song.mp3",
    singer: "Bruno Mars",
    title: "The Lazy Song",
    duration: 0,
  },
  {
    name: "Bruno Mars - Treasure.mp3",
    path: "/audio/Bruno%20Mars%20-%20Treasure.mp3",
    singer: "Bruno Mars",
    title: "Treasure",
    duration: 0,
  },
  {
    name: "Bruno Mars - Versace on The Floor [Official Audio].mp3",
    path: "/audio/Bruno%20Mars%20-%20Versace%20on%20The%20Floor%20%5BOfficial%20Audio%5D.mp3",
    singer: "Bruno Mars",
    title: "Versace on The Floor [Official Audio]",
    duration: 0,
  },
  {
    name: "Bruno_Mars_When_I_Was_Your_Man_Official_Video_.mp3",
    path: "/audio/Bruno_Mars_When_I_Was_Your_Man_Official_Video_.mp3",
    singer: "Bruno_Mars_When_I_Was_Your_Man_Official_Video_.mp3",
    title: "Bruno_Mars_When_I_Was_Your_Man_Official_Video_.mp3",
    duration: 0,
  },
  {
    name: "Bryan Adams - Heaven.mp3",
    path: "/audio/Bryan%20Adams%20-%20Heaven.mp3",
    singer: "Bryan Adams",
    title: "Heaven",
    duration: 0,
  },
  {
    name: "Bunga Citra Lestari - 05 Aku Dan Dirimu (Feat. Ari Lasso).mp3",
    path: "/audio/Bunga%20Citra%20Lestari%20-%2005%20Aku%20Dan%20Dirimu%20(Feat.%20Ari%20Lasso).mp3",
    singer: "Bunga Citra Lestari",
    title: "05 Aku Dan Dirimu (Feat. Ari Lasso)",
    duration: 0,
  },
  {
    name: "CAMELIA 2.mp3",
    path: "/audio/CAMELIA%202.mp3",
    singer: "CAMELIA 2.mp3",
    title: "CAMELIA 2.mp3",
    duration: 0,
  },
  {
    name: "CINTA DAN BENCI.mp3",
    path: "/audio/CINTA%20DAN%20BENCI.mp3",
    singer: "CINTA DAN BENCI.mp3",
    title: "CINTA DAN BENCI.mp3",
    duration: 0,
  },
  {
    name: "CINTA PUTIH.mp3",
    path: "/audio/CINTA%20PUTIH.mp3",
    singer: "CINTA PUTIH.mp3",
    title: "CINTA PUTIH.mp3",
    duration: 0,
  },
  {
    name: "Calum Scott - You Are The Reason Official.mp3",
    path: "/audio/Calum%20Scott%20-%20You%20Are%20The%20Reason%20Official.mp3",
    singer: "Calum Scott",
    title: "You Are The Reason Official",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - All That.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20All%20That.mp3",
    singer: "Carly Rae Jepsen",
    title: "All That",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Both Sides Now.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Both%20Sides%20Now.mp3",
    singer: "Carly Rae Jepsen",
    title: "Both Sides Now",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Call Me Maybe.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Call%20Me%20Maybe.mp3",
    singer: "Carly Rae Jepsen",
    title: "Call Me Maybe",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Cry.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Cry.mp3",
    singer: "Carly Rae Jepsen",
    title: "Cry",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Cut To The Feeling.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Cut%20To%20The%20Feeling.mp3",
    singer: "Carly Rae Jepsen",
    title: "Cut To The Feeling",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Drive.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Drive.mp3",
    singer: "Carly Rae Jepsen",
    title: "Drive",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Emotion.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Emotion.mp3",
    singer: "Carly Rae Jepsen",
    title: "Emotion",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - First Time.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20First%20Time.mp3",
    singer: "Carly Rae Jepsen",
    title: "First Time",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Gimmie Love (1).mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Gimmie%20Love%20(1).mp3",
    singer: "Carly Rae Jepsen",
    title: "Gimmie Love (1)",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Higher.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Higher.mp3",
    singer: "Carly Rae Jepsen",
    title: "Higher",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - I Really Like You.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20I%20Really%20Like%20You.mp3",
    singer: "Carly Rae Jepsen",
    title: "I Really Like You",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - More Than A Memory.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20More%20Than%20A%20Memory.mp3",
    singer: "Carly Rae Jepsen",
    title: "More Than A Memory",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Never Get To Hold You.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Never%20Get%20To%20Hold%20You.mp3",
    singer: "Carly Rae Jepsen",
    title: "Never Get To Hold You",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - No Drug Like Me.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20No%20Drug%20Like%20Me.mp3",
    singer: "Carly Rae Jepsen",
    title: "No Drug Like Me",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Party For One.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Party%20For%20One.mp3",
    singer: "Carly Rae Jepsen",
    title: "Party For One",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Stay Away.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Stay%20Away.mp3",
    singer: "Carly Rae Jepsen",
    title: "Stay Away",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Summer Love.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Summer%20Love.mp3",
    singer: "Carly Rae Jepsen",
    title: "Summer Love",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Sweetie.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Sweetie.mp3",
    singer: "Carly Rae Jepsen",
    title: "Sweetie",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Talk To Me.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Talk%20To%20Me.mp3",
    singer: "Carly Rae Jepsen",
    title: "Talk To Me",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - This Kiss.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20This%20Kiss.mp3",
    singer: "Carly Rae Jepsen",
    title: "This Kiss",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Too Much.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Too%20Much.mp3",
    singer: "Carly Rae Jepsen",
    title: "Too Much",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Tug of War.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Tug%20of%20War.mp3",
    singer: "Carly Rae Jepsen",
    title: "Tug of War",
    duration: 0,
  },
  {
    name: "Carly Rae Jepsen - Turn Me Up.mp3",
    path: "/audio/Carly%20Rae%20Jepsen%20-%20Turn%20Me%20Up.mp3",
    singer: "Carly Rae Jepsen",
    title: "Turn Me Up",
    duration: 0,
  },
  {
    name: "Cashmere Cat - Quit (Lyric Video) ft. Ariana Grande.mp3",
    path: "/audio/Cashmere%20Cat%20-%20Quit%20(Lyric%20Video)%20ft.%20Ariana%20Grande.mp3",
    singer: "Cashmere Cat",
    title: "Quit (Lyric Video) ft. Ariana Grande",
    duration: 0,
  },
  {
    name: "Celine Dion & Peabo Bryson - Beauty And The Beast (HQ Official Music Video) (256 kbps).mp3",
    path: "/audio/Celine%20Dion%20%26%20Peabo%20Bryson%20-%20Beauty%20And%20The%20Beast%20(HQ%20Official%20Music%20Video)%20(256%20kbps).mp3",
    singer: "Celine Dion & Peabo Bryson",
    title: "Beauty And The Beast (HQ Official Music Video) (256 kbps)",
    duration: 0,
  },
  {
    name: "Celine Dion - Just walk away.mp3",
    path: "/audio/Celine%20Dion%20-%20Just%20walk%20away.mp3",
    singer: "Celine Dion",
    title: "Just walk away",
    duration: 0,
  },
  {
    name: "Celine Dion - the power of love Celine Dion Edward y Bella subtitulada espaсol.wmv - YouTube.mp3",
    path: "/audio/Celine%20Dion%20-%20the%20power%20of%20love%20Celine%20Dion%20Edward%20y%20Bella%20subtitulada%20espa%D1%81ol.wmv%20-%20YouTube.mp3",
    singer: "Celine Dion",
    title:
      "the power of love Celine Dion Edward y Bella subtitulada espaсol.wmv - YouTube",
    duration: 0,
  },
  {
    name: "Chad_Crouch_-_Shipping_Lanes.mp3",
    path: "/audio/Chad_Crouch_-_Shipping_Lanes.mp3",
    singer: "Chad_Crouch_-_Shipping_Lanes.mp3",
    title: "Chad_Crouch_-_Shipping_Lanes.mp3",
    duration: 0,
  },
  {
    name: "Chandelier-Sia.mp3",
    path: "/audio/Chandelier-Sia.mp3",
    singer: "Chandelier-Sia.mp3",
    title: "Chandelier-Sia.mp3",
    duration: 0,
  },
  {
    name: "Charlie Puth - ATTANTION.mp3",
    path: "/audio/Charlie%20Puth%20-%20ATTANTION.mp3",
    singer: "Charlie Puth",
    title: "ATTANTION",
    duration: 0,
  },
  {
    name: "Charlie Puth - How Long.mp3",
    path: "/audio/Charlie%20Puth%20-%20How%20Long.mp3",
    singer: "Charlie Puth",
    title: "How Long",
    duration: 0,
  },
  {
    name: "Charlie Puth - One Call Away.mp3",
    path: "/audio/Charlie%20Puth%20-%20One%20Call%20Away.mp3",
    singer: "Charlie Puth",
    title: "One Call Away",
    duration: 0,
  },
  {
    name: "Cheat Codes - No Promises ft. Demi Lovato [Official Video].mp3",
    path: "/audio/Cheat%20Codes%20-%20No%20Promises%20ft.%20Demi%20Lovato%20%5BOfficial%20Video%5D.mp3",
    singer: "Cheat Codes",
    title: "No Promises ft. Demi Lovato [Official Video]",
    duration: 0,
  },
  {
    name: "Christina Perry - Burning Gold.mp3",
    path: "/audio/Christina%20Perry%20-%20Burning%20Gold.mp3",
    singer: "Christina Perry",
    title: "Burning Gold",
    duration: 0,
  },
  {
    name: "Christina Perry - Human.mp3",
    path: "/audio/Christina%20Perry%20-%20Human.mp3",
    singer: "Christina Perry",
    title: "Human",
    duration: 0,
  },
  {
    name: "Christina Perry - Penguin.mp3",
    path: "/audio/Christina%20Perry%20-%20Penguin.mp3",
    singer: "Christina Perry",
    title: "Penguin",
    duration: 0,
  },
  {
    name: "Christina Perry - Sad Song.mp3",
    path: "/audio/Christina%20Perry%20-%20Sad%20Song.mp3",
    singer: "Christina Perry",
    title: "Sad Song",
    duration: 0,
  },
  {
    name: "Christina Perry - Thousand Years +++.mp3",
    path: "/audio/Christina%20Perry%20-%20Thousand%20Years%20%2B%2B%2B.mp3",
    singer: "Christina Perry",
    title: "Thousand Years +++",
    duration: 0,
  },
  {
    name: "Christina Perry - Tragedy.mp3",
    path: "/audio/Christina%20Perry%20-%20Tragedy.mp3",
    singer: "Christina Perry",
    title: "Tragedy",
    duration: 0,
  },
  {
    name: "Chrisye - Anak Sekolah.mp3",
    path: "/audio/Chrisye%20-%20Anak%20Sekolah.mp3",
    singer: "Chrisye",
    title: "Anak Sekolah",
    duration: 0,
  },
  {
    name: "City of Stars (Duet ft. Ryan Gosling, Emma Stone) - La La Land Original Motion Picture Soundtrack.mp3",
    path: "/audio/City%20of%20Stars%20(Duet%20ft.%20Ryan%20Gosling%2C%20Emma%20Stone)%20-%20La%20La%20Land%20Original%20Motion%20Picture%20Soundtrack.mp3",
    singer: "City of Stars (Duet ft. Ryan Gosling, Emma Stone)",
    title: "La La Land Original Motion Picture Soundtrack",
    duration: 0,
  },
  {
    name: "Clean Bandit - Symphony feat. Zara Larsson [Official Video].mp3",
    path: "/audio/Clean%20Bandit%20-%20Symphony%20feat.%20Zara%20Larsson%20%5BOfficial%20Video%5D.mp3",
    singer: "Clean Bandit",
    title: "Symphony feat. Zara Larsson [Official Video]",
    duration: 0,
  },
  {
    name: "Close to you.mp3",
    path: "/audio/Close%20to%20you.mp3",
    singer: "Close to you.mp3",
    title: "Close to you.mp3",
    duration: 0,
  },
  {
    name: "Coldplay - Everglow (Single Version) - Official video.mp3",
    path: "/audio/Coldplay%20-%20Everglow%20(Single%20Version)%20-%20Official%20video.mp3",
    singer: "Coldplay",
    title: "Everglow (Single Version) - Official video",
    duration: 0,
  },
  {
    name: "Coldplay - Miracles.mp3",
    path: "/audio/Coldplay%20-%20Miracles.mp3",
    singer: "Coldplay",
    title: "Miracles",
    duration: 0,
  },
  {
    name: "Coldplay - True Love.mp3",
    path: "/audio/Coldplay%20-%20True%20Love.mp3",
    singer: "Coldplay",
    title: "True Love",
    duration: 0,
  },
  {
    name: "Come Away With Me-Norah Jones.mp3",
    path: "/audio/Come%20Away%20With%20Me-Norah%20Jones.mp3",
    singer: "Come Away With Me-Norah Jones.mp3",
    title: "Come Away With Me-Norah Jones.mp3",
    duration: 0,
  },
  {
    name: "Complicated.mp3",
    path: "/audio/Complicated.mp3",
    singer: "Complicated.mp3",
    title: "Complicated.mp3",
    duration: 0,
  },
  {
    name: "Country Roads - JohnDenver.mp3",
    path: "/audio/Country%20Roads%20-%20JohnDenver.mp3",
    singer: "Country Roads",
    title: "JohnDenver",
    duration: 0,
  },
  {
    name: "Crazy.mp3",
    path: "/audio/Crazy.mp3",
    singer: "Crazy.mp3",
    title: "Crazy.mp3",
    duration: 0,
  },
  {
    name: "Céline Dion - A New Day Has Come.mp3",
    path: "/audio/C%C3%A9line%20Dion%20-%20A%20New%20Day%20Has%20Come.mp3",
    singer: "Céline Dion",
    title: "A New Day Has Come",
    duration: 0,
  },
  {
    name: "Céline Dion - All By Myself (Official Remastered HD Video) (256 kbps).mp3",
    path: "/audio/C%C3%A9line%20Dion%20-%20All%20By%20Myself%20(Official%20Remastered%20HD%20Video)%20(256%20kbps).mp3",
    singer: "Céline Dion",
    title: "All By Myself (Official Remastered HD Video) (256 kbps)",
    duration: 0,
  },
  {
    name: "Céline Dion - Because You Love Me.mp3",
    path: "/audio/C%C3%A9line%20Dion%20-%20Because%20You%20Love%20Me.mp3",
    singer: "Céline Dion",
    title: "Because You Love Me",
    duration: 0,
  },
  {
    name: "Céline Dion - I'm Alive.mp3",
    path: "/audio/C%C3%A9line%20Dion%20-%20I'm%20Alive.mp3",
    singer: "Céline Dion",
    title: "I'm Alive",
    duration: 0,
  },
  {
    name: "Céline Dion - That's The Way It Is (Upscale 1080p 60fps Enhanced) (256 kbps).mp3",
    path: "/audio/C%C3%A9line%20Dion%20-%20That's%20The%20Way%20It%20Is%20(Upscale%201080p%2060fps%20Enhanced)%20(256%20kbps).mp3",
    singer: "Céline Dion",
    title: "That's The Way It Is (Upscale 1080p 60fps Enhanced) (256 kbps)",
    duration: 0,
  },
  {
    name: "Céline Dion - The Power Of Love (Official Video) (256 kbps).mp3",
    path: "/audio/C%C3%A9line%20Dion%20-%20The%20Power%20Of%20Love%20(Official%20Video)%20(256%20kbps).mp3",
    singer: "Céline Dion",
    title: "The Power Of Love (Official Video) (256 kbps)",
    duration: 0,
  },
  {
    name: "Céline Dion and R. Kelly - I'm Your Angel (Official Music Video, Studio Version) [1080p] (256 kbps).mp3",
    path: "/audio/C%C3%A9line%20Dion%20and%20R.%20Kelly%20-%20I'm%20Your%20Angel%20(Official%20Music%20Video%2C%20Studio%20Version)%20%5B1080p%5D%20(256%20kbps).mp3",
    singer: "Céline Dion and R. Kelly",
    title:
      "I'm Your Angel (Official Music Video, Studio Version) [1080p] (256 kbps)",
    duration: 0,
  },
  {
    name: "DIBATAS KOTA INI.mp3",
    path: "/audio/DIBATAS%20KOTA%20INI.mp3",
    singer: "DIBATAS KOTA INI.mp3",
    title: "DIBATAS KOTA INI.mp3",
    duration: 0,
  },
  {
    name: "Dewa 19 - Risalah Hati.mp3",
    path: "/audio/Dewa%2019%20-%20Risalah%20Hati.mp3",
    singer: "Dewa 19",
    title: "Risalah Hati",
    duration: 0,
  },
  {
    name: "Distance ft Jason Mraz.mp3",
    path: "/audio/Distance%20ft%20Jason%20Mraz.mp3",
    singer: "Distance ft Jason Mraz.mp3",
    title: "Distance ft Jason Mraz.mp3",
    duration: 0,
  },
  {
    name: "Disturbia.mp3",
    path: "/audio/Disturbia.mp3",
    singer: "Disturbia.mp3",
    title: "Disturbia.mp3",
    duration: 0,
  },
  {
    name: "Don't You Remember.mp3",
    path: "/audio/Don't%20You%20Remember.mp3",
    singer: "Don't You Remember.mp3",
    title: "Don't You Remember.mp3",
    duration: 0,
  },
  {
    name: "Don't tell me stories - Saskia Serge.mp3",
    path: "/audio/Don't%20tell%20me%20stories%20-%20Saskia%20Serge.mp3",
    singer: "Don't tell me stories",
    title: "Saskia Serge",
    duration: 0,
  },
  {
    name: "Dua Lipa - New Rules (Official Music Video).mp3",
    path: "/audio/Dua%20Lipa%20-%20New%20Rules%20(Official%20Music%20Video).mp3",
    singer: "Dua Lipa",
    title: "New Rules (Official Music Video)",
    duration: 0,
  },
  {
    name: "EBIET G ADE = Aku Ingin PuLang.mp3",
    path: "/audio/EBIET%20G%20ADE%20%3D%20Aku%20Ingin%20PuLang.mp3",
    singer: "EBIET G ADE = Aku Ingin PuLang.mp3",
    title: "EBIET G ADE = Aku Ingin PuLang.mp3",
    duration: 0,
  },
  {
    name: "EBIET G ADE = Titip Rindu Buat Ayah.mp3",
    path: "/audio/EBIET%20G%20ADE%20%3D%20Titip%20Rindu%20Buat%20Ayah.mp3",
    singer: "EBIET G ADE = Titip Rindu Buat Ayah.mp3",
    title: "EBIET G ADE = Titip Rindu Buat Ayah.mp3",
    duration: 0,
  },
  {
    name: "EBIET-Berita Kepada .mp3",
    path: "/audio/EBIET-Berita%20Kepada%20.mp3",
    singer: "EBIET-Berita Kepada .mp3",
    title: "EBIET-Berita Kepada .mp3",
    duration: 0,
  },
  {
    name: "Ebiet G Ade - Untuk Kita Renungkan.mp3",
    path: "/audio/Ebiet%20G%20Ade%20-%20Untuk%20Kita%20Renungkan.mp3",
    singer: "Ebiet G Ade",
    title: "Untuk Kita Renungkan",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Bad Habits.mp3",
    path: "/audio/Ed%20Sheeran%20-%20Bad%20Habits.mp3",
    singer: "Ed Sheeran",
    title: "Bad Habits",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Bloodstream.mp3",
    path: "/audio/Ed%20Sheeran%20-%20Bloodstream.mp3",
    singer: "Ed Sheeran",
    title: "Bloodstream",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Castle on the Hill.mp3",
    path: "/audio/Ed%20Sheeran%20-%20Castle%20on%20the%20Hill.mp3",
    singer: "Ed Sheeran",
    title: "Castle on the Hill",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Dive [Official Audio].mp3",
    path: "/audio/Ed%20Sheeran%20-%20Dive%20%5BOfficial%20Audio%5D.mp3",
    singer: "Ed Sheeran",
    title: "Dive [Official Audio]",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Don't.mp3",
    path: "/audio/Ed%20Sheeran%20-%20Don't.mp3",
    singer: "Ed Sheeran",
    title: "Don't",
    duration: 0,
  },
  {
    name: "Ed Sheeran - How Would You Feel (Paean).mp3",
    path: "/audio/Ed%20Sheeran%20-%20How%20Would%20You%20Feel%20(Paean).mp3",
    singer: "Ed Sheeran",
    title: "How Would You Feel (Paean)",
    duration: 0,
  },
  {
    name: "Ed Sheeran - I See Fire.mp3",
    path: "/audio/Ed%20Sheeran%20-%20I%20See%20Fire.mp3",
    singer: "Ed Sheeran",
    title: "I See Fire",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Nancy Mulligan.mp3",
    path: "/audio/Ed%20Sheeran%20-%20Nancy%20Mulligan.mp3",
    singer: "Ed Sheeran",
    title: "Nancy Mulligan",
    duration: 0,
  },
  {
    name: "Ed Sheeran - New Man.mp3",
    path: "/audio/Ed%20Sheeran%20-%20New%20Man.mp3",
    singer: "Ed Sheeran",
    title: "New Man",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Perfect [Official Audio].mp3",
    path: "/audio/Ed%20Sheeran%20-%20Perfect%20%5BOfficial%20Audio%5D.mp3",
    singer: "Ed Sheeran",
    title: "Perfect [Official Audio]",
    duration: 0,
  },
  {
    name: "Ed Sheeran - Thinking Out Loud (1) (1).mp3",
    path: "/audio/Ed%20Sheeran%20-%20Thinking%20Out%20Loud%20(1)%20(1).mp3",
    singer: "Ed Sheeran",
    title: "Thinking Out Loud (1) (1)",
    duration: 0,
  },
  {
    name: "Elegi Esok Pagi.mp3",
    path: "/audio/Elegi%20Esok%20Pagi.mp3",
    singer: "Elegi Esok Pagi.mp3",
    title: "Elegi Esok Pagi.mp3",
    duration: 0,
  },
  {
    name: "Ellie Goulding - Love Me Like You Do -- Pop.mp3",
    path: "/audio/Ellie%20Goulding%20-%20Love%20Me%20Like%20You%20Do%20--%20Pop.mp3",
    singer: "Ellie Goulding",
    title: "Love Me Like You Do -- Pop",
    duration: 0,
  },
  {
    name: "Ellie Goulding - wemp3.net - On My Mind.mp3",
    path: "/audio/Ellie%20Goulding%20-%20wemp3.net%20-%20On%20My%20Mind.mp3",
    singer: "Ellie Goulding",
    title: "wemp3.net - On My Mind",
    duration: 0,
  },
  {
    name: "Give Me More Time - Nicole.mp3",
    path: "/audio/Give%20Me%20More%20Time%20-%20Nicole.mp3",
    singer: "Give Me More Time",
    title: "Nicole",
    duration: 0,
  },
  {
    name: "Glenn Fredly - Terserah.mp3",
    path: "/audio/Glenn%20Fredly%20-%20Terserah.mp3",
    singer: "Glenn Fredly",
    title: "Terserah",
    duration: 0,
  },
  {
    name: "Greatest Love Of All.mp3",
    path: "/audio/Greatest%20Love%20Of%20All.mp3",
    singer: "Greatest Love Of All.mp3",
    title: "Greatest Love Of All.mp3",
    duration: 0,
  },
  {
    name: "Gunroses Don'tc~1.mp3",
    path: "/audio/Gunroses%20Don'tc~1.mp3",
    singer: "Gunroses Don'tc~1.mp3",
    title: "Gunroses Don'tc~1.mp3",
    duration: 0,
  },
  {
    name: "Gunsn Roses Novemb~1.mp3",
    path: "/audio/Gunsn%20Roses%20Novemb~1.mp3",
    singer: "Gunsn Roses Novemb~1.mp3",
    title: "Gunsn Roses Novemb~1.mp3",
    duration: 0,
  },
  {
    name: "Hard To Say I'm Sorry.mp3",
    path: "/audio/Hard%20To%20Say%20I'm%20Sorry.mp3",
    singer: "Hard To Say I'm Sorry.mp3",
    title: "Hard To Say I'm Sorry.mp3",
    duration: 0,
  },
  {
    name: "Heavy (Official Video) - Linkin Park (feat. Kiiara).mp3",
    path: "/audio/Heavy%20(Official%20Video)%20-%20Linkin%20Park%20(feat.%20Kiiara).mp3",
    singer: "Heavy (Official Video)",
    title: "Linkin Park (feat. Kiiara)",
    duration: 0,
  },
  {
    name: "Hello.mp3",
    path: "/audio/Hello.mp3",
    singer: "Hello.mp3",
    title: "Hello.mp3",
    duration: 0,
  },
  {
    name: "Hoobastank - Disappear.mp3",
    path: "/audio/Hoobastank%20-%20Disappear.mp3",
    singer: "Hoobastank",
    title: "Disappear",
    duration: 0,
  },
  {
    name: "Human.mp3",
    path: "/audio/Human.mp3",
    singer: "Human.mp3",
    title: "Human.mp3",
    duration: 0,
  },
  {
    name: "I Gotta Know What's Going On.mp3",
    path: "/audio/I%20Gotta%20Know%20What's%20Going%20On.mp3",
    singer: "I Gotta Know What's Going On.mp3",
    title: "I Gotta Know What's Going On.mp3",
    duration: 0,
  },
  {
    name: "I believe.mp3",
    path: "/audio/I%20believe.mp3",
    singer: "I believe.mp3",
    title: "I believe.mp3",
    duration: 0,
  },
  {
    name: "JANGAN ADA DUSTA DI ANTARA KITA.mp3",
    path: "/audio/JANGAN%20ADA%20DUSTA%20DI%20ANTARA%20KITA.mp3",
    singer: "JANGAN ADA DUSTA DI ANTARA KITA.mp3",
    title: "JANGAN ADA DUSTA DI ANTARA KITA.mp3",
    duration: 0,
  },
  {
    name: "Jangan Memilih Aku.mp3",
    path: "/audio/Jangan%20Memilih%20Aku.mp3",
    singer: "Jangan Memilih Aku.mp3",
    title: "Jangan Memilih Aku.mp3",
    duration: 0,
  },
  {
    name: "Jar Of Hearts.mp3",
    path: "/audio/Jar%20Of%20Hearts.mp3",
    singer: "Jar Of Hearts.mp3",
    title: "Jar Of Hearts.mp3",
    duration: 0,
  },
  {
    name: "Jasmine_Thompson_-_La_La_La_ft_Sam_Smith_Naughty_Boy_Cover_(cloud-vibe.com).mp3",
    path: "/audio/Jasmine_Thompson_-_La_La_La_ft_Sam_Smith_Naughty_Boy_Cover_(cloud-vibe.com).mp3",
    singer:
      "Jasmine_Thompson_-_La_La_La_ft_Sam_Smith_Naughty_Boy_Cover_(cloud-vibe.com).mp3",
    title:
      "Jasmine_Thompson_-_La_La_La_ft_Sam_Smith_Naughty_Boy_Cover_(cloud-vibe.com).mp3",
    duration: 0,
  },
  {
    name: "Jasmine_Thompson_-_Love_The_Way_You_Lie_Rihanna_cover_(cloud-vibe.com).mp3",
    path: "/audio/Jasmine_Thompson_-_Love_The_Way_You_Lie_Rihanna_cover_(cloud-vibe.com).mp3",
    singer:
      "Jasmine_Thompson_-_Love_The_Way_You_Lie_Rihanna_cover_(cloud-vibe.com).mp3",
    title:
      "Jasmine_Thompson_-_Love_The_Way_You_Lie_Rihanna_cover_(cloud-vibe.com).mp3",
    duration: 0,
  },
  {
    name: "Jasmine_Thompson_-_Wrecking_Ball_Miley_Cyrus_Cover_(cloud-vibe.com).mp3",
    path: "/audio/Jasmine_Thompson_-_Wrecking_Ball_Miley_Cyrus_Cover_(cloud-vibe.com).mp3",
    singer:
      "Jasmine_Thompson_-_Wrecking_Ball_Miley_Cyrus_Cover_(cloud-vibe.com).mp3",
    title:
      "Jasmine_Thompson_-_Wrecking_Ball_Miley_Cyrus_Cover_(cloud-vibe.com).mp3",
    duration: 0,
  },
  {
    name: "Jason Mraz - 3 Things.mp3",
    path: "/audio/Jason%20Mraz%20-%203%20Things.mp3",
    singer: "Jason Mraz",
    title: "3 Things",
    duration: 0,
  },
  {
    name: "Jason Mraz - 93 Million Miles.mp3",
    path: "/audio/Jason%20Mraz%20-%2093%20Million%20Miles.mp3",
    singer: "Jason Mraz",
    title: "93 Million Miles",
    duration: 0,
  },
  {
    name: "Jason Mraz - Bella Luna.mp3",
    path: "/audio/Jason%20Mraz%20-%20Bella%20Luna.mp3",
    singer: "Jason Mraz",
    title: "Bella Luna",
    duration: 0,
  },
  {
    name: "Jason Mraz - Best Friend.mp3",
    path: "/audio/Jason%20Mraz%20-%20Best%20Friend.mp3",
    singer: "Jason Mraz",
    title: "Best Friend",
    duration: 0,
  },
  {
    name: "Jason Mraz - Butterfly.mp3",
    path: "/audio/Jason%20Mraz%20-%20Butterfly.mp3",
    singer: "Jason Mraz",
    title: "Butterfly",
    duration: 0,
  },
  {
    name: "Jason Mraz - I Won't Give Up.mp3",
    path: "/audio/Jason%20Mraz%20-%20I%20Won't%20Give%20Up.mp3",
    singer: "Jason Mraz",
    title: "I Won't Give Up",
    duration: 0,
  },
  {
    name: "Jason Mraz - I'm Yours.mp3",
    path: "/audio/Jason%20Mraz%20-%20I'm%20Yours.mp3",
    singer: "Jason Mraz",
    title: "I'm Yours",
    duration: 0,
  },
  {
    name: "Jason Mraz - Life Is Wonderful.mp3",
    path: "/audio/Jason%20Mraz%20-%20Life%20Is%20Wonderful.mp3",
    singer: "Jason Mraz",
    title: "Life Is Wonderful",
    duration: 0,
  },
  {
    name: "Jason Mraz - Lucky (feat. Colbie Caillat) [Official Video].mp3",
    path: "/audio/Jason%20Mraz%20-%20Lucky%20(feat.%20Colbie%20Caillat)%20%5BOfficial%20Video%5D.mp3",
    singer: "Jason Mraz",
    title: "Lucky (feat. Colbie Caillat) [Official Video]",
    duration: 0,
  },
  {
    name: "Jason Mraz - Out of My Hands.mp3",
    path: "/audio/Jason%20Mraz%20-%20Out%20of%20My%20Hands.mp3",
    singer: "Jason Mraz",
    title: "Out of My Hands",
    duration: 0,
  },
  {
    name: "Jason Mraz - The Woman I Love.mp3",
    path: "/audio/Jason%20Mraz%20-%20The%20Woman%20I%20Love.mp3",
    singer: "Jason Mraz",
    title: "The Woman I Love",
    duration: 0,
  },
  {
    name: "Jessie J - Do It Like a Dude.mp3",
    path: "/audio/Jessie%20J%20-%20Do%20It%20Like%20a%20Dude.mp3",
    singer: "Jessie J",
    title: "Do It Like a Dude",
    duration: 0,
  },
  {
    name: "Jessie J - Domino.mp3",
    path: "/audio/Jessie%20J%20-%20Domino.mp3",
    singer: "Jessie J",
    title: "Domino",
    duration: 0,
  },
  {
    name: "Jessie J - Fire.mp3",
    path: "/audio/Jessie%20J%20-%20Fire.mp3",
    singer: "Jessie J",
    title: "Fire",
    duration: 0,
  },
  {
    name: "Jessie J - Get Away.mp3",
    path: "/audio/Jessie%20J%20-%20Get%20Away.mp3",
    singer: "Jessie J",
    title: "Get Away",
    duration: 0,
  },
  {
    name: "Jessie J - Hero.mp3",
    path: "/audio/Jessie%20J%20-%20Hero.mp3",
    singer: "Jessie J",
    title: "Hero",
    duration: 0,
  },
  {
    name: "Jessie J - I Got You (I Feel Good).mp3",
    path: "/audio/Jessie%20J%20-%20I%20Got%20You%20(I%20Feel%20Good).mp3",
    singer: "Jessie J",
    title: "I Got You (I Feel Good)",
    duration: 0,
  },
  {
    name: "Jessie J - Masterpiece.mp3",
    path: "/audio/Jessie%20J%20-%20Masterpiece.mp3",
    singer: "Jessie J",
    title: "Masterpiece",
    duration: 0,
  },
  {
    name: "Jessie J - Nobody's Perfect.mp3",
    path: "/audio/Jessie%20J%20-%20Nobody's%20Perfect.mp3",
    singer: "Jessie J",
    title: "Nobody's Perfect",
    duration: 0,
  },
  {
    name: "Jessie J - Price Tag.mp3",
    path: "/audio/Jessie%20J%20-%20Price%20Tag.mp3",
    singer: "Jessie J",
    title: "Price Tag",
    duration: 0,
  },
  {
    name: "Jessie J - Sexy Silk.mp3",
    path: "/audio/Jessie%20J%20-%20Sexy%20Silk.mp3",
    singer: "Jessie J",
    title: "Sexy Silk",
    duration: 0,
  },
  {
    name: "Jessie J - Sweet Talker.mp3",
    path: "/audio/Jessie%20J%20-%20Sweet%20Talker.mp3",
    singer: "Jessie J",
    title: "Sweet Talker",
    duration: 0,
  },
  {
    name: "Jessie J - Thunder.mp3",
    path: "/audio/Jessie%20J%20-%20Thunder.mp3",
    singer: "Jessie J",
    title: "Thunder",
    duration: 0,
  },
  {
    name: "Jessie J - Who You Are.mp3",
    path: "/audio/Jessie%20J%20-%20Who%20You%20Are.mp3",
    singer: "Jessie J",
    title: "Who You Are",
    duration: 0,
  },
  {
    name: "Jessie J - Who's Laughing Now.mp3",
    path: "/audio/Jessie%20J%20-%20Who's%20Laughing%20Now.mp3",
    singer: "Jessie J",
    title: "Who's Laughing Now",
    duration: 0,
  },
  {
    name: "Jessie-J - Flashlight.mp3",
    path: "/audio/Jessie-J%20-%20Flashlight.mp3",
    singer: "Jessie-J",
    title: "Flashlight",
    duration: 0,
  },
  {
    name: "John Denver - Annie Song .mp3",
    path: "/audio/John%20Denver%20-%20Annie%20Song%20.mp3",
    singer: "John Denver",
    title: "Annie Song ",
    duration: 0,
  },
  {
    name: "John Lennon - Jealous Guy .mp3",
    path: "/audio/John%20Lennon%20-%20Jealous%20Guy%20.mp3",
    singer: "John Lennon",
    title: "Jealous Guy ",
    duration: 0,
  },
  {
    name: "John Lennon - Mother .mp3",
    path: "/audio/John%20Lennon%20-%20Mother%20.mp3",
    singer: "John Lennon",
    title: "Mother ",
    duration: 0,
  },
  {
    name: "John Lennon - Woman  .mp3",
    path: "/audio/John%20Lennon%20-%20Woman%20%20.mp3",
    singer: "John Lennon",
    title: "Woman  ",
    duration: 0,
  },
  {
    name: "John Lenon - Imagine.wav",
    path: "/audio/John%20Lenon%20-%20Imagine.wav",
    singer: "John Lenon",
    title: "Imagine",
    duration: 0,
  },
  {
    name: "Judika-Apakah+Ini+Cinta.mp3",
    path: "/audio/Judika-Apakah%2BIni%2BCinta.mp3",
    singer: "Judika-Apakah+Ini+Cinta.mp3",
    title: "Judika-Apakah+Ini+Cinta.mp3",
    duration: 0,
  },
  {
    name: "Judika_Aku_Yang_Tersakiti.mp3",
    path: "/audio/Judika_Aku_Yang_Tersakiti.mp3",
    singer: "Judika_Aku_Yang_Tersakiti.mp3",
    title: "Judika_Aku_Yang_Tersakiti.mp3",
    duration: 0,
  },
  {
    name: "Judika_Ft_Duma_Sampai_Akhir.mp3",
    path: "/audio/Judika_Ft_Duma_Sampai_Akhir.mp3",
    singer: "Judika_Ft_Duma_Sampai_Akhir.mp3",
    title: "Judika_Ft_Duma_Sampai_Akhir.mp3",
    duration: 0,
  },
  {
    name: "Judika_Mama_Papa_Larang_Mapala.mp3",
    path: "/audio/Judika_Mama_Papa_Larang_Mapala.mp3",
    singer: "Judika_Mama_Papa_Larang_Mapala.mp3",
    title: "Judika_Mama_Papa_Larang_Mapala.mp3",
    duration: 0,
  },
  {
    name: "Justin Bieber - Love Your Self.mp3",
    path: "/audio/Justin%20Bieber%20-%20Love%20Your%20Self.mp3",
    singer: "Justin Bieber",
    title: "Love Your Self",
    duration: 0,
  },
  {
    name: "Justin Bieber - Sorry.mp3",
    path: "/audio/Justin%20Bieber%20-%20Sorry.mp3",
    singer: "Justin Bieber",
    title: "Sorry",
    duration: 0,
  },
  {
    name: "Justin Timberlake - Can't Stop The Feeling! (Original Song From Dreamworks Animation's _Trolls_).mp3",
    path: "/audio/Justin%20Timberlake%20-%20Can't%20Stop%20The%20Feeling!%20(Original%20Song%20From%20Dreamworks%20Animation's%20_Trolls_).mp3",
    singer: "Justin Timberlake",
    title:
      "Can't Stop The Feeling! (Original Song From Dreamworks Animation's _Trolls_)",
    duration: 0,
  },
  {
    name: "Justin Timberlake - Cry Me a River.mp3",
    path: "/audio/Justin%20Timberlake%20-%20Cry%20Me%20a%20River.mp3",
    singer: "Justin Timberlake",
    title: "Cry Me a River",
    duration: 0,
  },
  {
    name: "Justin_Bieber_-_Yummy_(Lyrics)(128k).mp3",
    path: "/audio/Justin_Bieber_-_Yummy_(Lyrics)(128k).mp3",
    singer: "Justin_Bieber_-_Yummy_(Lyrics)(128k).mp3",
    title: "Justin_Bieber_-_Yummy_(Lyrics)(128k).mp3",
    duration: 0,
  },
  {
    name: "KUCARI JALAN TERBAIK.mp3",
    path: "/audio/KUCARI%20JALAN%20TERBAIK.mp3",
    singer: "KUCARI JALAN TERBAIK.mp3",
    title: "KUCARI JALAN TERBAIK.mp3",
    duration: 0,
  },
  {
    name: "KUPU-KUPU HITAM PUTIH.mp3",
    path: "/audio/KUPU-KUPU%20HITAM%20PUTIH.mp3",
    singer: "KUPU-KUPU HITAM PUTIH.mp3",
    title: "KUPU-KUPU HITAM PUTIH.mp3",
    duration: 0,
  },
  {
    name: "KUPU-KUPU KERTAS.mp3",
    path: "/audio/KUPU-KUPU%20KERTAS.mp3",
    singer: "KUPU-KUPU KERTAS.mp3",
    title: "KUPU-KUPU KERTAS.mp3",
    duration: 0,
  },
  {
    name: "KUPU-KUPU MALAM.mp3",
    path: "/audio/KUPU-KUPU%20MALAM.mp3",
    singer: "KUPU-KUPU MALAM.mp3",
    title: "KUPU-KUPU MALAM.mp3",
    duration: 0,
  },
  {
    name: "Katy Perry - Bon Appétit ft. Migos.mp3",
    path: "/audio/Katy%20Perry%20-%20Bon%20App%C3%A9tit%20ft.%20Migos.mp3",
    singer: "Katy Perry",
    title: "Bon Appétit ft. Migos",
    duration: 0,
  },
  {
    name: "Katy Perry - California Girls (feat. Snoop Dogg).mp3",
    path: "/audio/Katy%20Perry%20-%20California%20Girls%20(feat.%20Snoop%20Dogg).mp3",
    singer: "Katy Perry",
    title: "California Girls (feat. Snoop Dogg)",
    duration: 0,
  },
  {
    name: "Kotak - Bayang Abadi.mp3",
    path: "/audio/Kotak%20-%20Bayang%20Abadi.mp3",
    singer: "Kotak",
    title: "Bayang Abadi",
    duration: 0,
  },
  {
    name: "Kotak - Mencintai Ku Dan Dia.mp3",
    path: "/audio/Kotak%20-%20Mencintai%20Ku%20Dan%20Dia.mp3",
    singer: "Kotak",
    title: "Mencintai Ku Dan Dia",
    duration: 0,
  },
  {
    name: "Kotak - Sendiri (Bonys Track).mp3",
    path: "/audio/Kotak%20-%20Sendiri%20(Bonys%20Track).mp3",
    singer: "Kotak",
    title: "Sendiri (Bonys Track)",
    duration: 0,
  },
  {
    name: "Kotak - Tetap Ada.mp3",
    path: "/audio/Kotak%20-%20Tetap%20Ada.mp3",
    singer: "Kotak",
    title: "Tetap Ada",
    duration: 0,
  },
  {
    name: "Kotak - Tinggalkan Saja.mp3",
    path: "/audio/Kotak%20-%20Tinggalkan%20Saja.mp3",
    singer: "Kotak",
    title: "Tinggalkan Saja",
    duration: 0,
  },
  {
    name: "Kotak_-_01._Terbang_(New_Version).mp3",
    path: "/audio/Kotak_-_01._Terbang_(New_Version).mp3",
    singer: "Kotak_-_01._Terbang_(New_Version).mp3",
    title: "Kotak_-_01._Terbang_(New_Version).mp3",
    duration: 0,
  },
  {
    name: "Kotak_Kecuali_Kamu.mp3",
    path: "/audio/Kotak_Kecuali_Kamu.mp3",
    singer: "Kotak_Kecuali_Kamu.mp3",
    title: "Kotak_Kecuali_Kamu.mp3",
    duration: 0,
  },
  {
    name: "Kotak_Saat_Kau_Jauh.mp3",
    path: "/audio/Kotak_Saat_Kau_Jauh.mp3",
    singer: "Kotak_Saat_Kau_Jauh.mp3",
    title: "Kotak_Saat_Kau_Jauh.mp3",
    duration: 0,
  },
  {
    name: "Krisdayanti - Cobalah Untuk Setia.mp3",
    path: "/audio/Krisdayanti%20-%20Cobalah%20Untuk%20Setia.mp3",
    singer: "Krisdayanti",
    title: "Cobalah Untuk Setia",
    duration: 0,
  },
  {
    name: "Krisdayanti - Mencintaimu.mp3",
    path: "/audio/Krisdayanti%20-%20Mencintaimu.mp3",
    singer: "Krisdayanti",
    title: "Mencintaimu",
    duration: 0,
  },
  {
    name: "Krisdayanti - Yang Kumau.mp3",
    path: "/audio/Krisdayanti%20-%20Yang%20Kumau.mp3",
    singer: "Krisdayanti",
    title: "Yang Kumau",
    duration: 0,
  },
  {
    name: "Krisdayanti feat. Melly Goeslaw - Cinta.mp3",
    path: "/audio/Krisdayanti%20feat.%20Melly%20Goeslaw%20-%20Cinta.mp3",
    singer: "Krisdayanti feat. Melly Goeslaw",
    title: "Cinta",
    duration: 0,
  },
  {
    name: "LAGU RINDU.mp3",
    path: "/audio/LAGU%20RINDU.mp3",
    singer: "LAGU RINDU.mp3",
    title: "LAGU RINDU.mp3",
    duration: 0,
  },
  {
    name: "LAGUF1.MOBI - Bruno Mars- Count on me (lyrics).mp3",
    path: "/audio/LAGUF1.MOBI%20-%20Bruno%20Mars-%20Count%20on%20me%20(lyrics).mp3",
    singer: "LAGUF1.MOBI",
    title: "Bruno Mars- Count on me (lyrics)",
    duration: 0,
  },
  {
    name: "Lagu Untuk Sebuah Nama.mp3",
    path: "/audio/Lagu%20Untuk%20Sebuah%20Nama.mp3",
    singer: "Lagu Untuk Sebuah Nama.mp3",
    title: "Lagu Untuk Sebuah Nama.mp3",
    duration: 0,
  },
  {
    name: "Last Child - Anak kecil.mp3",
    path: "/audio/Last%20Child%20-%20Anak%20kecil.mp3",
    singer: "Last Child",
    title: "Anak kecil",
    duration: 0,
  },
  {
    name: "Last_Child_-_Tak_Pernah_Ternilai_cover_(_Keesamus_).mp3",
    path: "/audio/Last_Child_-_Tak_Pernah_Ternilai_cover_(_Keesamus_).mp3",
    singer: "Last_Child_-_Tak_Pernah_Ternilai_cover_(_Keesamus_).mp3",
    title: "Last_Child_-_Tak_Pernah_Ternilai_cover_(_Keesamus_).mp3",
    duration: 0,
  },
  {
    name: "Last_Child_Sekuat_Hatimu.mp3",
    path: "/audio/Last_Child_Sekuat_Hatimu.mp3",
    singer: "Last_Child_Sekuat_Hatimu.mp3",
    title: "Last_Child_Sekuat_Hatimu.mp3",
    duration: 0,
  },
  {
    name: "Last_Child_Tak_Pernah_Ternilai.mp3",
    path: "/audio/Last_Child_Tak_Pernah_Ternilai.mp3",
    singer: "Last_Child_Tak_Pernah_Ternilai.mp3",
    title: "Last_Child_Tak_Pernah_Ternilai.mp3",
    duration: 0,
  },
  {
    name: "Last_Shild_Ft_Giselle_Seluruh_Nafas_Ini.mp3",
    path: "/audio/Last_Shild_Ft_Giselle_Seluruh_Nafas_Ini.mp3",
    singer: "Last_Shild_Ft_Giselle_Seluruh_Nafas_Ini.mp3",
    title: "Last_Shild_Ft_Giselle_Seluruh_Nafas_Ini.mp3",
    duration: 0,
  },
  {
    name: "M2M_the day you went.mp3",
    path: "/audio/M2M_the%20day%20you%20went.mp3",
    singer: "M2M_the day you went.mp3",
    title: "M2M_the day you went.mp3",
    duration: 0,
  },
  {
    name: "MAROON 5 this love.mp3",
    path: "/audio/MAROON%205%20this%20love.mp3",
    singer: "MAROON 5 this love.mp3",
    title: "MAROON 5 this love.mp3",
    duration: 0,
  },
  {
    name: "METALLICA - Nothing Else Matters.mp3",
    path: "/audio/METALLICA%20-%20Nothing%20Else%20Matters.mp3",
    singer: "METALLICA",
    title: "Nothing Else Matters",
    duration: 0,
  },
  {
    name: "METALLICA - The Unforgiven.mp3",
    path: "/audio/METALLICA%20-%20The%20Unforgiven.mp3",
    singer: "METALLICA",
    title: "The Unforgiven",
    duration: 0,
  },
  {
    name: "Maha Dewi - Risalah Hati.mp3",
    path: "/audio/Maha%20Dewi%20-%20Risalah%20Hati.mp3",
    singer: "Maha Dewi",
    title: "Risalah Hati",
    duration: 0,
  },
  {
    name: "Mariah Carey - Hero.mp3",
    path: "/audio/Mariah%20Carey%20-%20Hero.mp3",
    singer: "Mariah Carey",
    title: "Hero",
    duration: 0,
  },
  {
    name: "Mariah Carey - Without You.mp3",
    path: "/audio/Mariah%20Carey%20-%20Without%20You.mp3",
    singer: "Mariah Carey",
    title: "Without You",
    duration: 0,
  },
  {
    name: "Maroon 5 - Girls Like You.mp3",
    path: "/audio/Maroon%205%20-%20Girls%20Like%20You.mp3",
    singer: "Maroon 5",
    title: "Girls Like You",
    duration: 0,
  },
  {
    name: "Maroon 5 - Harder To Breathe.mp3",
    path: "/audio/Maroon%205%20-%20Harder%20To%20Breathe.mp3",
    singer: "Maroon 5",
    title: "Harder To Breathe",
    duration: 0,
  },
  {
    name: "Maroon 5 - Moves Likes Jagger.MP3",
    path: "/audio/Maroon%205%20-%20Moves%20Likes%20Jagger.MP3",
    singer: "Maroon 5",
    title: "Moves Likes Jagger",
    duration: 0,
  },
  {
    name: "Maroon 5 - She will be loved.mp3",
    path: "/audio/Maroon%205%20-%20She%20will%20be%20loved.mp3",
    singer: "Maroon 5",
    title: "She will be loved",
    duration: 0,
  },
  {
    name: "Million Years Ago (Alan Morris Remix).mp3",
    path: "/audio/Million%20Years%20Ago%20(Alan%20Morris%20Remix).mp3",
    singer: "Million Years Ago (Alan Morris Remix).mp3",
    title: "Million Years Ago (Alan Morris Remix).mp3",
    duration: 0,
  },
  {
    name: "Mino sayko arigato - Ka-Ka-Ka-Kawai (zaycev.net).mp3",
    path: "/audio/Mino%20sayko%20arigato%20-%20Ka-Ka-Ka-Kawai%20(zaycev.net).mp3",
    singer: "Mino sayko arigato",
    title: "Ka-Ka-Ka-Kawai (zaycev.net)",
    duration: 0,
  },
  {
    name: "More Than I Can Say.mp3",
    path: "/audio/More%20Than%20I%20Can%20Say.mp3",
    singer: "More Than I Can Say.mp3",
    title: "More Than I Can Say.mp3",
    duration: 0,
  },
  {
    name: "More Than Words.mp3",
    path: "/audio/More%20Than%20Words.mp3",
    singer: "More Than Words.mp3",
    title: "More Than Words.mp3",
    duration: 0,
  },
  {
    name: "Nike Ardilla - Bintang Kehidupan.mp3",
    path: "/audio/Nike%20Ardilla%20-%20Bintang%20Kehidupan.mp3",
    singer: "Nike Ardilla",
    title: "Bintang Kehidupan",
    duration: 0,
  },
  {
    name: "Nike Ardilla - Fantasia Bulan Madu (Cinta Kita).mp3",
    path: "/audio/Nike%20Ardilla%20-%20Fantasia%20Bulan%20Madu%20(Cinta%20Kita).mp3",
    singer: "Nike Ardilla",
    title: "Fantasia Bulan Madu (Cinta Kita)",
    duration: 0,
  },
  {
    name: "Nike Ardilla - Sandiwara Cinta.mp3",
    path: "/audio/Nike%20Ardilla%20-%20Sandiwara%20Cinta.mp3",
    singer: "Nike Ardilla",
    title: "Sandiwara Cinta",
    duration: 0,
  },
  {
    name: "Nike Ardilla - Seberkas Sinar.mp3",
    path: "/audio/Nike%20Ardilla%20-%20Seberkas%20Sinar.mp3",
    singer: "Nike Ardilla",
    title: "Seberkas Sinar",
    duration: 0,
  },
  {
    name: "Nike Ardilla - Suara Hatiku.mp3",
    path: "/audio/Nike%20Ardilla%20-%20Suara%20Hatiku.mp3",
    singer: "Nike Ardilla",
    title: "Suara Hatiku",
    duration: 0,
  },
  {
    name: "Nike ardila.mp3",
    path: "/audio/Nike%20ardila.mp3",
    singer: "Nike ardila.mp3",
    title: "Nike ardila.mp3",
    duration: 0,
  },
  {
    name: "Nike_Ardilla_Mama_Aku_Ingin_Pulang.mp3",
    path: "/audio/Nike_Ardilla_Mama_Aku_Ingin_Pulang.mp3",
    singer: "Nike_Ardilla_Mama_Aku_Ingin_Pulang.mp3",
    title: "Nike_Ardilla_Mama_Aku_Ingin_Pulang.mp3",
    duration: 0,
  },
  {
    name: "Nobody But You - Alain Barriebe.mp3",
    path: "/audio/Nobody%20But%20You%20-%20Alain%20Barriebe.mp3",
    singer: "Nobody But You",
    title: "Alain Barriebe",
    duration: 0,
  },
  {
    name: "Nobody's Child.mp3",
    path: "/audio/Nobody's%20Child.mp3",
    singer: "Nobody's Child.mp3",
    title: "Nobody's Child.mp3",
    duration: 0,
  },
  {
    name: "Norah Jones - Chasing Pirates.mp3",
    path: "/audio/Norah%20Jones%20-%20Chasing%20Pirates.mp3",
    singer: "Norah Jones",
    title: "Chasing Pirates",
    duration: 0,
  },
  {
    name: "Norah Jones - Don't Know Why (320 kbps).mp3",
    path: "/audio/Norah%20Jones%20-%20Don't%20Know%20Why%20(320%20kbps).mp3",
    singer: "Norah Jones",
    title: "Don't Know Why (320 kbps)",
    duration: 0,
  },
  {
    name: "Norah Jones - Nightingale.mp3",
    path: "/audio/Norah%20Jones%20-%20Nightingale.mp3",
    singer: "Norah Jones",
    title: "Nightingale",
    duration: 0,
  },
  {
    name: "Norah Jones - Sunrise (320 kbps).mp3",
    path: "/audio/Norah%20Jones%20-%20Sunrise%20(320%20kbps).mp3",
    singer: "Norah Jones",
    title: "Sunrise (320 kbps)",
    duration: 0,
  },
  {
    name: "Norah Jones - Sunrise.mp3",
    path: "/audio/Norah%20Jones%20-%20Sunrise.mp3",
    singer: "Norah Jones",
    title: "Sunrise",
    duration: 0,
  },
  {
    name: "Norah Jones - Those Sweet Words.mp3",
    path: "/audio/Norah%20Jones%20-%20Those%20Sweet%20Words.mp3",
    singer: "Norah Jones",
    title: "Those Sweet Words",
    duration: 0,
  },
  {
    name: "Norah Jones - What Am I To You_ (320 kbps).mp3",
    path: "/audio/Norah%20Jones%20-%20What%20Am%20I%20To%20You_%20(320%20kbps).mp3",
    singer: "Norah Jones",
    title: "What Am I To You_ (320 kbps)",
    duration: 0,
  },
  {
    name: "Norah Jones _ Shoot The Moon.mp3",
    path: "/audio/Norah%20Jones%20_%20Shoot%20The%20Moon.mp3",
    singer: "Norah Jones _ Shoot The Moon.mp3",
    title: "Norah Jones _ Shoot The Moon.mp3",
    duration: 0,
  },
  {
    name: "November Rain - Gun N Roses.mp3",
    path: "/audio/November%20Rain%20-%20Gun%20N%20Roses.mp3",
    singer: "November Rain",
    title: "Gun N Roses",
    duration: 0,
  },
  {
    name: "On The Floor New.MP3",
    path: "/audio/On%20The%20Floor%20New.MP3",
    singer: "On The Floor New.MP3",
    title: "On The Floor New.MP3",
    duration: 0,
  },
  {
    name: "One Direction - More Than This.wav",
    path: "/audio/One%20Direction%20-%20More%20Than%20This.wav",
    singer: "One Direction",
    title: "More Than This",
    duration: 0,
  },
  {
    name: "One Direction - Story of My Life-320k.mp3",
    path: "/audio/One%20Direction%20-%20Story%20of%20My%20Life-320k.mp3",
    singer: "One Direction",
    title: "Story of My Life-320k",
    duration: 0,
  },
  {
    name: "OneRepublic - 01 - Counting Stars - Copy (2).mp3",
    path: "/audio/OneRepublic%20-%2001%20-%20Counting%20Stars%20-%20Copy%20(2).mp3",
    singer: "OneRepublic",
    title: "01 - Counting Stars - Copy (2)",
    duration: 0,
  },
  {
    name: "PANCE F PONDAAG - Ku Cari Jalan Terbaik.mp3",
    path: "/audio/PANCE%20F%20PONDAAG%20-%20Ku%20Cari%20Jalan%20Terbaik.mp3",
    singer: "PANCE F PONDAAG",
    title: "Ku Cari Jalan Terbaik",
    duration: 0,
  },
  {
    name: "PERIH.mp3",
    path: "/audio/PERIH.mp3",
    singer: "PERIH.mp3",
    title: "PERIH.mp3",
    duration: 0,
  },
  {
    name: "Pance Kau Telah Berdua.mp3",
    path: "/audio/Pance%20Kau%20Telah%20Berdua.mp3",
    singer: "Pance Kau Telah Berdua.mp3",
    title: "Pance Kau Telah Berdua.mp3",
    duration: 0,
  },
  {
    name: "Passenger_Cover_by_Jasmine_Thompson_-_Let_her_go_cover_(cloud-vibe.com).mp3",
    path: "/audio/Passenger_Cover_by_Jasmine_Thompson_-_Let_her_go_cover_(cloud-vibe.com).mp3",
    singer:
      "Passenger_Cover_by_Jasmine_Thompson_-_Let_her_go_cover_(cloud-vibe.com).mp3",
    title:
      "Passenger_Cover_by_Jasmine_Thompson_-_Let_her_go_cover_(cloud-vibe.com).mp3",
    duration: 0,
  },
  {
    name: "Please Forgive Me - Bryan Adams.mp3",
    path: "/audio/Please%20Forgive%20Me%20-%20Bryan%20Adams.mp3",
    singer: "Please Forgive Me",
    title: "Bryan Adams",
    duration: 0,
  },
  {
    name: "Please Release me.mp3",
    path: "/audio/Please%20Release%20me.mp3",
    singer: "Please Release me.mp3",
    title: "Please Release me.mp3",
    duration: 0,
  },
  {
    name: "Poppy_Mercury_Surat_Undangan.mp3",
    path: "/audio/Poppy_Mercury_Surat_Undangan.mp3",
    singer: "Poppy_Mercury_Surat_Undangan.mp3",
    title: "Poppy_Mercury_Surat_Undangan.mp3",
    duration: 0,
  },
  {
    name: "Price Tag.mp3",
    path: "/audio/Price%20Tag.mp3",
    singer: "Price Tag.mp3",
    title: "Price Tag.mp3",
    duration: 0,
  },
  {
    name: "Put Your Head On My Shoulder.mp3",
    path: "/audio/Put%20Your%20Head%20On%20My%20Shoulder.mp3",
    singer: "Put Your Head On My Shoulder.mp3",
    title: "Put Your Head On My Shoulder.mp3",
    duration: 0,
  },
  {
    name: "ROSSA - TAK SANGGUP LAGI.mp3",
    path: "/audio/ROSSA%20-%20TAK%20SANGGUP%20LAGI.mp3",
    singer: "ROSSA",
    title: "TAK SANGGUP LAGI",
    duration: 0,
  },
  {
    name: "Rap God.mp3",
    path: "/audio/Rap%20God.mp3",
    singer: "Rap God.mp3",
    title: "Rap God.mp3",
    duration: 0,
  },
  {
    name: "Reflections Of My Life.mp3",
    path: "/audio/Reflections%20Of%20My%20Life.mp3",
    singer: "Reflections Of My Life.mp3",
    title: "Reflections Of My Life.mp3",
    duration: 0,
  },
  {
    name: "Rihanna - Don't Stop The Music.mp3",
    path: "/audio/Rihanna%20-%20Don't%20Stop%20The%20Music.mp3",
    singer: "Rihanna",
    title: "Don't Stop The Music",
    duration: 0,
  },
  {
    name: "Rihanna - Farewell.mp3",
    path: "/audio/Rihanna%20-%20Farewell.mp3",
    singer: "Rihanna",
    title: "Farewell",
    duration: 0,
  },
  {
    name: "Rihanna - Fool in Love.mp3",
    path: "/audio/Rihanna%20-%20Fool%20in%20Love.mp3",
    singer: "Rihanna",
    title: "Fool in Love",
    duration: 0,
  },
  {
    name: "Rihanna - Love The Way You Lie [Eminem ft. Rihanna].mp3",
    path: "/audio/Rihanna%20-%20Love%20The%20Way%20You%20Lie%20%5BEminem%20ft.%20Rihanna%5D.mp3",
    singer: "Rihanna",
    title: "Love The Way You Lie [Eminem ft. Rihanna]",
    duration: 0,
  },
  {
    name: "Rihanna - Man Down.mp3",
    path: "/audio/Rihanna%20-%20Man%20Down.mp3",
    singer: "Rihanna",
    title: "Man Down",
    duration: 0,
  },
  {
    name: "Rihanna - Rihanna - Diamonds.mp3",
    path: "/audio/Rihanna%20-%20Rihanna%20-%20Diamonds.mp3",
    singer: "Rihanna",
    title: "Rihanna - Diamonds",
    duration: 0,
  },
  {
    name: "Rihanna - Roc Me Out.mp3",
    path: "/audio/Rihanna%20-%20Roc%20Me%20Out.mp3",
    singer: "Rihanna",
    title: "Roc Me Out",
    duration: 0,
  },
  {
    name: "Rihanna - Russian Roulette - Rihanna.mp3",
    path: "/audio/Rihanna%20-%20Russian%20Roulette%20-%20Rihanna.mp3",
    singer: "Rihanna",
    title: "Russian Roulette - Rihanna",
    duration: 0,
  },
  {
    name: "Rihanna - Umbrella.mp3",
    path: "/audio/Rihanna%20-%20Umbrella.mp3",
    singer: "Rihanna",
    title: "Umbrella",
    duration: 0,
  },
  {
    name: "Rihanna - Where Have You Been.mp3",
    path: "/audio/Rihanna%20-%20Where%20Have%20You%20Been.mp3",
    singer: "Rihanna",
    title: "Where Have You Been",
    duration: 0,
  },
  {
    name: "Rolling in the deep.mp3",
    path: "/audio/Rolling%20in%20the%20deep.mp3",
    singer: "Rolling in the deep.mp3",
    title: "Rolling in the deep.mp3",
    duration: 0,
  },
  {
    name: "Rossa - Hati Yang Kau Sakiti.mp3",
    path: "/audio/Rossa%20-%20Hati%20Yang%20Kau%20Sakiti.mp3",
    singer: "Rossa",
    title: "Hati Yang Kau Sakiti",
    duration: 0,
  },
  {
    name: "Rossa - Ku Menunggu.mp3",
    path: "/audio/Rossa%20-%20Ku%20Menunggu.mp3",
    singer: "Rossa",
    title: "Ku Menunggu",
    duration: 0,
  },
  {
    name: "Rossa+-+Pudar.mp3",
    path: "/audio/Rossa%2B-%2BPudar.mp3",
    singer: "Rossa+-+Pudar.mp3",
    title: "Rossa+-+Pudar.mp3",
    duration: 0,
  },
  {
    name: "SCOPION - WHITE DOVE.MP3",
    path: "/audio/SCOPION%20-%20WHITE%20DOVE.MP3",
    singer: "SCOPION",
    title: "WHITE DOVE",
    duration: 0,
  },
  {
    name: "SCORPION - UNDER THE SAME SUN.MP3",
    path: "/audio/SCORPION%20-%20UNDER%20THE%20SAME%20SUN.MP3",
    singer: "SCORPION",
    title: "UNDER THE SAME SUN",
    duration: 0,
  },
  {
    name: "SCORPION - YOU AND  I.MP3",
    path: "/audio/SCORPION%20-%20YOU%20AND%20%20I.MP3",
    singer: "SCORPION",
    title: "YOU AND  I",
    duration: 0,
  },
  {
    name: "SELURUH NAFAS INI.mp3",
    path: "/audio/SELURUH%20NAFAS%20INI.mp3",
    singer: "SELURUH NAFAS INI.mp3",
    title: "SELURUH NAFAS INI.mp3",
    duration: 0,
  },
  {
    name: "SEMPURNA.mp3",
    path: "/audio/SEMPURNA.mp3",
    singer: "SEMPURNA.mp3",
    title: "SEMPURNA.mp3",
    duration: 0,
  },
  {
    name: "Sacrifice - Elton John.mp3",
    path: "/audio/Sacrifice%20-%20Elton%20John.mp3",
    singer: "Sacrifice",
    title: "Elton John",
    duration: 0,
  },
  {
    name: "Scorpions (Acoustica) - Holiday.mp3",
    path: "/audio/Scorpions%20(Acoustica)%20-%20Holiday.mp3",
    singer: "Scorpions (Acoustica)",
    title: "Holiday",
    duration: 0,
  },
  {
    name: "Scorpions - Always Somewhere.mp3",
    path: "/audio/Scorpions%20-%20Always%20Somewhere.mp3",
    singer: "Scorpions",
    title: "Always Somewhere",
    duration: 0,
  },
  {
    name: "Scorpions - Still Loving You.mp3",
    path: "/audio/Scorpions%20-%20Still%20Loving%20You.mp3",
    singer: "Scorpions",
    title: "Still Loving You",
    duration: 0,
  },
  {
    name: "Scorpions Send Me An Angel.mp3",
    path: "/audio/Scorpions%20Send%20Me%20An%20Angel.mp3",
    singer: "Scorpions Send Me An Angel.mp3",
    title: "Scorpions Send Me An Angel.mp3",
    duration: 0,
  },
  {
    name: "Scorpions_-_Wind_of_Change__ac.mp3",
    path: "/audio/Scorpions_-_Wind_of_Change__ac.mp3",
    singer: "Scorpions_-_Wind_of_Change__ac.mp3",
    title: "Scorpions_-_Wind_of_Change__ac.mp3",
    duration: 0,
  },
  {
    name: "Scorpions_-_You_and_I__acousti.mp3",
    path: "/audio/Scorpions_-_You_and_I__acousti.mp3",
    singer: "Scorpions_-_You_and_I__acousti.mp3",
    title: "Scorpions_-_You_and_I__acousti.mp3",
    duration: 0,
  },
  {
    name: "Set fire to The Rain.mp3",
    path: "/audio/Set%20fire%20to%20The%20Rain.mp3",
    singer: "Set fire to The Rain.mp3",
    title: "Set fire to The Rain.mp3",
    duration: 0,
  },
  {
    name: "She's Out Of My Life.mp3",
    path: "/audio/She's%20Out%20Of%20My%20Life.mp3",
    singer: "She's Out Of My Life.mp3",
    title: "She's Out Of My Life.mp3",
    duration: 0,
  },
  {
    name: "Simple Plan - Last One Standing.mp3",
    path: "/audio/Simple%20Plan%20-%20Last%20One%20Standing.mp3",
    singer: "Simple Plan",
    title: "Last One Standing",
    duration: 0,
  },
  {
    name: "Simple Plan - Welcome To My Life.mp3",
    path: "/audio/Simple%20Plan%20-%20Welcome%20To%20My%20Life.mp3",
    singer: "Simple Plan",
    title: "Welcome To My Life",
    duration: 0,
  },
  {
    name: "Simple Plan - You Suck at Love.mp3",
    path: "/audio/Simple%20Plan%20-%20You%20Suck%20at%20Love.mp3",
    singer: "Simple Plan",
    title: "You Suck at Love",
    duration: 0,
  },
  {
    name: "Someone Like You.mp3",
    path: "/audio/Someone%20Like%20You.mp3",
    singer: "Someone Like You.mp3",
    title: "Someone Like You.mp3",
    duration: 0,
  },
  {
    name: "TAK LEKANG OLEH WAKTU.mp3",
    path: "/audio/TAK%20LEKANG%20OLEH%20WAKTU.mp3",
    singer: "TAK LEKANG OLEH WAKTU.mp3",
    title: "TAK LEKANG OLEH WAKTU.mp3",
    duration: 0,
  },
  {
    name: "TERTATIH.mp3",
    path: "/audio/TERTATIH.mp3",
    singer: "TERTATIH.mp3",
    title: "TERTATIH.mp3",
    duration: 0,
  },
  {
    name: "Tata Janeeta - Penipu Hati.mp3",
    path: "/audio/Tata%20Janeeta%20-%20Penipu%20Hati.mp3",
    singer: "Tata Janeeta",
    title: "Penipu Hati",
    duration: 0,
  },
  {
    name: "Taylor Swift - ...Ready For It_  2017 (Pop Stars).mp3",
    path: "/audio/Taylor%20Swift%20-%20...Ready%20For%20It_%20%202017%20(Pop%20Stars).mp3",
    singer: "Taylor Swift",
    title: "...Ready For It_  2017 (Pop Stars)",
    duration: 0,
  },
  {
    name: "Taylor Swift - Back To December - Copy (2).mp3",
    path: "/audio/Taylor%20Swift%20-%20Back%20To%20December%20-%20Copy%20(2).mp3",
    singer: "Taylor Swift",
    title: "Back To December - Copy (2)",
    duration: 0,
  },
  {
    name: "Taylor Swift - Bad Blood (feat. Kendrick Lamar).mp3",
    path: "/audio/Taylor%20Swift%20-%20Bad%20Blood%20(feat.%20Kendrick%20Lamar).mp3",
    singer: "Taylor Swift",
    title: "Bad Blood (feat. Kendrick Lamar)",
    duration: 0,
  },
  {
    name: "Taylor Swift - Begin Again - Copy - Copy.mp3",
    path: "/audio/Taylor%20Swift%20-%20Begin%20Again%20-%20Copy%20-%20Copy.mp3",
    singer: "Taylor Swift",
    title: "Begin Again - Copy - Copy",
    duration: 0,
  },
  {
    name: "Taylor Swift - Blank Space.mp3",
    path: "/audio/Taylor%20Swift%20-%20Blank%20Space.mp3",
    singer: "Taylor Swift",
    title: "Blank Space",
    duration: 0,
  },
  {
    name: "Taylor Swift - Getaway Car 2017 (Pop Stars).mp3",
    path: "/audio/Taylor%20Swift%20-%20Getaway%20Car%202017%20(Pop%20Stars).mp3",
    singer: "Taylor Swift",
    title: "Getaway Car 2017 (Pop Stars)",
    duration: 0,
  },
  {
    name: "Taylor Swift - I Knew You Were Trouble.mp3",
    path: "/audio/Taylor%20Swift%20-%20I%20Knew%20You%20Were%20Trouble.mp3",
    singer: "Taylor Swift",
    title: "I Knew You Were Trouble",
    duration: 0,
  },
  {
    name: "Taylor Swift - Look What You Made Me Do.mp3",
    path: "/audio/Taylor%20Swift%20-%20Look%20What%20You%20Made%20Me%20Do.mp3",
    singer: "Taylor Swift",
    title: "Look What You Made Me Do",
    duration: 0,
  },
  {
    name: "Taylor Swift - Love Story.mp3",
    path: "/audio/Taylor%20Swift%20-%20Love%20Story.mp3",
    singer: "Taylor Swift",
    title: "Love Story",
    duration: 0,
  },
  {
    name: "Taylor Swift - Lover.mp3",
    path: "/audio/Taylor%20Swift%20-%20Lover.mp3",
    singer: "Taylor Swift",
    title: "Lover",
    duration: 0,
  },
  {
    name: "Taylor Swift - Shake It Off.mp3",
    path: "/audio/Taylor%20Swift%20-%20Shake%20It%20Off.mp3",
    singer: "Taylor Swift",
    title: "Shake It Off",
    duration: 0,
  },
  {
    name: "Taylor Swift - Wildest Dreams.mp3",
    path: "/audio/Taylor%20Swift%20-%20Wildest%20Dreams.mp3",
    singer: "Taylor Swift",
    title: "Wildest Dreams",
    duration: 0,
  },
  {
    name: "Taylor Swift - You Belong With Me.mp3",
    path: "/audio/Taylor%20Swift%20-%20You%20Belong%20With%20Me.mp3",
    singer: "Taylor Swift",
    title: "You Belong With Me",
    duration: 0,
  },
  {
    name: "Taylor Swift - willow.mp3",
    path: "/audio/Taylor%20Swift%20-%20willow.mp3",
    singer: "Taylor Swift",
    title: "willow",
    duration: 0,
  },
  {
    name: "Tentang Cinta ( Ipang ) Karaoke.mp3",
    path: "/audio/Tentang%20Cinta%20(%20Ipang%20)%20Karaoke.mp3",
    singer: "Tentang Cinta ( Ipang ) Karaoke.mp3",
    title: "Tentang Cinta ( Ipang ) Karaoke.mp3",
    duration: 0,
  },
  {
    name: "The Beatles - And I Love Her.mp3",
    path: "/audio/The%20Beatles%20-%20And%20I%20Love%20Her.mp3",
    singer: "The Beatles",
    title: "And I Love Her",
    duration: 0,
  },
  {
    name: "The Beatles - Hey Jude  .mp3",
    path: "/audio/The%20Beatles%20-%20Hey%20Jude%20%20.mp3",
    singer: "The Beatles",
    title: "Hey Jude  ",
    duration: 0,
  },
  {
    name: "The Beatles - Let It Be.mp3",
    path: "/audio/The%20Beatles%20-%20Let%20It%20Be.mp3",
    singer: "The Beatles",
    title: "Let It Be",
    duration: 0,
  },
  {
    name: "The Beatles - Yesterday.mp3",
    path: "/audio/The%20Beatles%20-%20Yesterday.mp3",
    singer: "The Beatles",
    title: "Yesterday",
    duration: 0,
  },
  {
    name: "The Beatles.mp3",
    path: "/audio/The%20Beatles.mp3",
    singer: "The Beatles.mp3",
    title: "The Beatles.mp3",
    duration: 0,
  },
  {
    name: "The Chainsmokers - Don't Let Me Down (Audio) ft. Daya.mp3",
    path: "/audio/The%20Chainsmokers%20-%20Don't%20Let%20Me%20Down%20(Audio)%20ft.%20Daya.mp3",
    singer: "The Chainsmokers",
    title: "Don't Let Me Down (Audio) ft. Daya",
    duration: 0,
  },
  {
    name: "The Chainsmokers Bloodstream.mp3",
    path: "/audio/The%20Chainsmokers%20Bloodstream.mp3",
    singer: "The Chainsmokers Bloodstream.mp3",
    title: "The Chainsmokers Bloodstream.mp3",
    duration: 0,
  },
  {
    name: "The Chainsmokers The One.mp3",
    path: "/audio/The%20Chainsmokers%20The%20One.mp3",
    singer: "The Chainsmokers The One.mp3",
    title: "The Chainsmokers The One.mp3",
    duration: 0,
  },
  {
    name: "The Lonely.mp3",
    path: "/audio/The%20Lonely.mp3",
    singer: "The Lonely.mp3",
    title: "The Lonely.mp3",
    duration: 0,
  },
  {
    name: "UNTUK SEBUAH NAMA.mp3",
    path: "/audio/UNTUK%20SEBUAH%20NAMA.mp3",
    singer: "UNTUK SEBUAH NAMA.mp3",
    title: "UNTUK SEBUAH NAMA.mp3",
    duration: 0,
  },
  {
    name: "Wake Up Alone(feat. Jhene Aiko).mp3",
    path: "/audio/Wake%20Up%20Alone(feat.%20Jhene%20Aiko).mp3",
    singer: "Wake Up Alone(feat. Jhene Aiko).mp3",
    title: "Wake Up Alone(feat. Jhene Aiko).mp3",
    duration: 0,
  },
  {
    name: "We Don't Talk Anymore.mp3",
    path: "/audio/We%20Don't%20Talk%20Anymore.mp3",
    singer: "We Don't Talk Anymore.mp3",
    title: "We Don't Talk Anymore.mp3",
    duration: 0,
  },
  {
    name: "Westlife - Flying Without Wings.mp3",
    path: "/audio/Westlife%20-%20Flying%20Without%20Wings.mp3",
    singer: "Westlife",
    title: "Flying Without Wings",
    duration: 0,
  },
  {
    name: "Westlife - I Cry.mp3",
    path: "/audio/Westlife%20-%20I%20Cry.mp3",
    singer: "Westlife",
    title: "I Cry",
    duration: 0,
  },
  {
    name: "Westlife - I Do.mp3",
    path: "/audio/Westlife%20-%20I%20Do.mp3",
    singer: "Westlife",
    title: "I Do",
    duration: 0,
  },
  {
    name: "Westlife - I Have A Dream.mp3",
    path: "/audio/Westlife%20-%20I%20Have%20A%20Dream.mp3",
    singer: "Westlife",
    title: "I Have A Dream",
    duration: 0,
  },
  {
    name: "Westlife - I Lay My Love on You.mp3",
    path: "/audio/Westlife%20-%20I%20Lay%20My%20Love%20on%20You.mp3",
    singer: "Westlife",
    title: "I Lay My Love on You",
    duration: 0,
  },
  {
    name: "Westlife - I Wanna Grow Old With You.mp3",
    path: "/audio/Westlife%20-%20I%20Wanna%20Grow%20Old%20With%20You.mp3",
    singer: "Westlife",
    title: "I Wanna Grow Old With You",
    duration: 0,
  },
  {
    name: "Westlife - If I Let U Go.mp3",
    path: "/audio/Westlife%20-%20If%20I%20Let%20U%20Go.mp3",
    singer: "Westlife",
    title: "If I Let U Go",
    duration: 0,
  },
  {
    name: "Westlife - My Love (acoustic version).mp3",
    path: "/audio/Westlife%20-%20My%20Love%20(acoustic%20version).mp3",
    singer: "Westlife",
    title: "My Love (acoustic version)",
    duration: 0,
  },
  {
    name: "Westlife - Nothing's Gonna Change My Love for You.mp3",
    path: "/audio/Westlife%20-%20Nothing's%20Gonna%20Change%20My%20Love%20for%20You.mp3",
    singer: "Westlife",
    title: "Nothing's Gonna Change My Love for You",
    duration: 0,
  },
  {
    name: "Westlife - Soledad.mp3",
    path: "/audio/Westlife%20-%20Soledad.mp3",
    singer: "Westlife",
    title: "Soledad",
    duration: 0,
  },
  {
    name: "Westlife - Us Against the World.mp3",
    path: "/audio/Westlife%20-%20Us%20Against%20the%20World.mp3",
    singer: "Westlife",
    title: "Us Against the World",
    duration: 0,
  },
  {
    name: "Westlife - What About Now.mp3",
    path: "/audio/Westlife%20-%20What%20About%20Now.mp3",
    singer: "Westlife",
    title: "What About Now",
    duration: 0,
  },
  {
    name: "Westlife - You Raise Me Up.mp3",
    path: "/audio/Westlife%20-%20You%20Raise%20Me%20Up.mp3",
    singer: "Westlife",
    title: "You Raise Me Up",
    duration: 0,
  },
  {
    name: "Westlife_I_Do_1 - Copy - Copy.mp3",
    path: "/audio/Westlife_I_Do_1%20-%20Copy%20-%20Copy.mp3",
    singer: "Westlife_I_Do_1",
    title: "Copy - Copy",
    duration: 0,
  },
  {
    name: "What Do You Mean - Justin Bieber (Lyrics).mp3",
    path: "/audio/What%20Do%20You%20Mean%20-%20Justin%20Bieber%20(Lyrics).mp3",
    singer: "What Do You Mean",
    title: "Justin Bieber (Lyrics)",
    duration: 0,
  },
  {
    name: "What Makes You Beautiful.mp3",
    path: "/audio/What%20Makes%20You%20Beautiful.mp3",
    singer: "What Makes You Beautiful.mp3",
    title: "What Makes You Beautiful.mp3",
    duration: 0,
  },
  {
    name: "When A Man Love A Woman.mp3",
    path: "/audio/When%20A%20Man%20Love%20A%20Woman.mp3",
    singer: "When A Man Love A Woman.mp3",
    title: "When A Man Love A Woman.mp3",
    duration: 0,
  },
  {
    name: "When I Need You.mp3",
    path: "/audio/When%20I%20Need%20You.mp3",
    singer: "When I Need You.mp3",
    title: "When I Need You.mp3",
    duration: 0,
  },
  {
    name: "When You’re Gone.mp3",
    path: "/audio/When%20You%E2%80%99re%20Gone.mp3",
    singer: "When You’re Gone.mp3",
    title: "When You’re Gone.mp3",
    duration: 0,
  },
  {
    name: "White_Lion_You_are_All_I_Need.mp3",
    path: "/audio/White_Lion_You_are_All_I_Need.mp3",
    singer: "White_Lion_You_are_All_I_Need.mp3",
    title: "White_Lion_You_are_All_I_Need.mp3",
    duration: 0,
  },
  {
    name: "Wish You Were Here.mp3",
    path: "/audio/Wish%20You%20Were%20Here.mp3",
    singer: "Wish You Were Here.mp3",
    title: "Wish You Were Here.mp3",
    duration: 0,
  },
  {
    name: "Wiz Khalifa - See You Again (Remix) (Feat. Trey Songz) -- R&B.mp3",
    path: "/audio/Wiz%20Khalifa%20-%20See%20You%20Again%20(Remix)%20(Feat.%20Trey%20Songz)%20--%20R%26B.mp3",
    singer: "Wiz Khalifa",
    title: "See You Again (Remix) (Feat. Trey Songz) -- R&B",
    duration: 0,
  },
  {
    name: "Yes You Do - Maureen Kelly.mp3",
    path: "/audio/Yes%20You%20Do%20-%20Maureen%20Kelly.mp3",
    singer: "Yes You Do",
    title: "Maureen Kelly",
    duration: 0,
  },
  {
    name: "You Are My Love.mp3",
    path: "/audio/You%20Are%20My%20Love.mp3",
    singer: "You Are My Love.mp3",
    title: "You Are My Love.mp3",
    duration: 0,
  },
  {
    name: "You Are.mp3",
    path: "/audio/You%20Are.mp3",
    singer: "You Are.mp3",
    title: "You Are.mp3",
    duration: 0,
  },
  {
    name: "You Mean Everything To Me.mp3",
    path: "/audio/You%20Mean%20Everything%20To%20Me.mp3",
    singer: "You Mean Everything To Me.mp3",
    title: "You Mean Everything To Me.mp3",
    duration: 0,
  },
  {
    name: "You Need Me.mp3",
    path: "/audio/You%20Need%20Me.mp3",
    singer: "You Need Me.mp3",
    title: "You Need Me.mp3",
    duration: 0,
  },
  {
    name: "You're My World.mp3",
    path: "/audio/You're%20My%20World.mp3",
    singer: "You're My World.mp3",
    title: "You're My World.mp3",
    duration: 0,
  },
  {
    name: "You're Still The One -SHANIA Twain.mp3",
    path: "/audio/You're%20Still%20The%20One%20-SHANIA%20Twain.mp3",
    singer: "You're Still The One -SHANIA Twain.mp3",
    title: "You're Still The One -SHANIA Twain.mp3",
    duration: 0,
  },
  {
    name: "You're the inspiration.mp3",
    path: "/audio/You're%20the%20inspiration.mp3",
    singer: "You're the inspiration.mp3",
    title: "You're the inspiration.mp3",
    duration: 0,
  },
  {
    name: "Yovie and Nuno - Janji Suci.mp3",
    path: "/audio/Yovie%20and%20Nuno%20-%20Janji%20Suci.mp3",
    singer: "Yovie and Nuno",
    title: "Janji Suci",
    duration: 0,
  },
];
