export const songs: string[] = [
  "500 Miles.mp3",
  "AKU TAK BIASA.mp3",
  "AUDY - MENANGIS SEMALAM.mp3",
  "AVRILL~4.MP3",
  "AYAT-AYAT CINTA.mp3",
  "Adele - Easy On Me (Official Video) (320 kbps).mp3",
  "Afgan - Jodoh Pasti Bertemu(Naufal Cover).mp3",
  "Akhirnya Ku Menemukanmu.mp3",
  "Alan Walker - Alone.mp3",
  "Alan Walker - Faded [pleer.com].mp3",
  "Alessia Cara  Im Yours Official Audio [Mp3Convert.Tube].mp3",
  "Alessia Cara - How Far I'll Go (Official Video).mp3",
  "Alessia Cara - Scars To Your Beautiful.mp3",
  "Am I Wrong-Nico ft. Vinz.mp3",
  "And I Love You.mp3",
  "Ariana Grande, John Legend - Beauty and the Beast (Lyrics).mp3",
  "Arms.mp3",
  "Avenged Sevenfold - Warmness On The Soul.mp3",
  "Avenged_Sevenfold_Afterlife.mp3",
  "Avenged_Sevenfold_MIA.mp3",
  "Avenged_Sevenfold_Until_The_End.mp3",
  "Avril Lavigne - Don’t Tell Me.mp3",
  "Avril Lavigne - Girlfriend (1).mp3",
  "Avril Lavigne - I'm With You (Album Version).mp3",
  "Avril Lavigne - My Happy Ending (live acoustic).mp3",
  "Avril Lavigne - Rock ’n’ Roll.mp3",
  "BALADA PENGANGGURAN.mp3",
  "BERSAMAMU.mp3",
  "BUKAN CINTA BIASA.mp3",
  "BUKAN DIA TAPI AKU.mp3",
  "BUKAN RAYUAN GOMBAL.mp3",
  "Back To December.mp3",
  "Bad Girl (feat. Marilyn Manson).mp3",
  "Bang Bang Bang.mp3",
  "Beautiful Piano Music Relaxing Music Romantic Music Sleep Music Study Music ★132.mp3",
  "Before The Next Teardrop Falls.mp3",
  "Berita Kepada Kawan.mp3",
  "Betharia Sonata - Hati Yang Luka.mp3",
  "Betharia Sonatha - Kau Tercipta Untukku.mp3",
  "Bettaria -.mp3",
  "Beyoncé - ALREADY.mp3",
  "Beyoncé - Amor Gitano ft. Alejandro Fernandez.mp3",
  "Beyoncé - BIGGER.mp3",
  "Beyoncé - Crazy In Love (50 оттенков серого).mp3",
  "Beyoncé - Crazy in Love (feat. Jay-Z).mp3",
  "Beyoncé - Drunk In Love (feat. Jay Z).mp3",
  "Beyoncé - FIND YOUR WAY BACK.mp3",
  "Beyoncé - Ghost_Haunted (ost Fifty Shades of Grey) (50  оттенков).mp3",
  "Beyoncé - Halo.mp3",
  "Beyoncé - If I Were A Boy.mp3",
  "Beyoncé - Irreplaceable.mp3",
  "Beyoncé - MOOD 4 EVA.mp3",
  "Beyoncé - NILE.mp3",
  "Beyoncé - Naughty Girl.mp3",
  "Beyoncé - Single Ladies (Put A Ring On I.mp3",
  "Beyoncé - Spirit.mp3",
  "Beyoncé - Survivor.mp3",
  "Bintang Kehidupan.mp3",
  "BonJovi-Always (DJ Crimp Remix).mp3",
  "Brian McKnight - Back At One.mp3",
  "Brian McKnight - Can You Stop The Rain.mp3",
  "Brian McKnight - Careless Whisper (feat. Kenny G).mp3",
  "Brian McKnight - Color of the Night.mp3",
  "Brian McKnight - For You (From _Superhero_) (2001).mp3",
  "Brian McKnight - More Than Wonderful (live).mp3",
  "Brian McKnight - Never Felt This Way.mp3",
  "Brian McKnight - Sweeter.mp3",
  "Brian McKnight - Win (1).mp3",
  "Brian McKnight - Win.mp3",
  "Brian McKnight Jr. - Marry Your Daughter.mp3",
  "Brian McKnight feat. Claude McKnight & Tim Miner - The First Noel.mp3",
  "Bright Eyes .mp3",
  "Bruno Mars - 24K Magic.mp3",
  "Bruno Mars - Count On Me.mp3",
  "Bruno Mars - Count on me (lyrics).mp3",
  "Bruno Mars - Grenade .mp3",
  "Bruno Mars - Grenade.mp3",
  "Bruno Mars - Just the Way You Are.mp3",
  "Bruno Mars - Locked Out Of Heaven.mp3",
  "Bruno Mars - Talking To The Moon.mp3",
  "Bruno Mars - That's What I Like.mp3",
  "Bruno Mars - The Lazy Song.mp3",
  "Bruno Mars - Treasure.mp3",
  "Bruno Mars - Versace on The Floor [Official Audio].mp3",
  "Bruno_Mars_When_I_Was_Your_Man_Official_Video_.mp3",
  "Bryan Adams - Heaven.mp3",
  "Bunga Citra Lestari - 05 Aku Dan Dirimu (Feat. Ari Lasso).mp3",
  "CAMELIA 2.mp3",
  "CINTA DAN BENCI.mp3",
  "CINTA PUTIH.mp3",
  "Calum Scott - You Are The Reason Official.mp3",
  "Carly Rae Jepsen - All That.mp3",
  "Carly Rae Jepsen - Both Sides Now.mp3",
  "Carly Rae Jepsen - Call Me Maybe.mp3",
  "Carly Rae Jepsen - Cry.mp3",
  "Carly Rae Jepsen - Cut To The Feeling.mp3",
  "Carly Rae Jepsen - Drive.mp3",
  "Carly Rae Jepsen - Emotion.mp3",
  "Carly Rae Jepsen - First Time.mp3",
  "Carly Rae Jepsen - Gimmie Love (1).mp3",
  "Carly Rae Jepsen - Higher.mp3",
  "Carly Rae Jepsen - I Really Like You.mp3",
  "Carly Rae Jepsen - More Than A Memory.mp3",
  "Carly Rae Jepsen - Never Get To Hold You.mp3",
  "Carly Rae Jepsen - No Drug Like Me.mp3",
  "Carly Rae Jepsen - Party For One.mp3",
  "Carly Rae Jepsen - Stay Away.mp3",
  "Carly Rae Jepsen - Summer Love.mp3",
  "Carly Rae Jepsen - Sweetie.mp3",
  "Carly Rae Jepsen - Talk To Me.mp3",
  "Carly Rae Jepsen - This Kiss.mp3",
  "Carly Rae Jepsen - Too Much.mp3",
  "Carly Rae Jepsen - Tug of War.mp3",
  "Carly Rae Jepsen - Turn Me Up.mp3",
  "Cashmere Cat - Quit (Lyric Video) ft. Ariana Grande.mp3",
  "Celine Dion & Peabo Bryson - Beauty And The Beast (HQ Official Music Video) (256 kbps).mp3",
  "Celine Dion - Just walk away.mp3",
  "Celine Dion - the power of love Celine Dion Edward y Bella subtitulada espaсol.wmv - YouTube.mp3",
  "Chad_Crouch_-_Shipping_Lanes.mp3",
  "Chandelier-Sia.mp3",
  "Charlie Puth - ATTANTION.mp3",
  "Charlie Puth - How Long.mp3",
  "Charlie Puth - One Call Away.mp3",
  "Cheat Codes - No Promises ft. Demi Lovato [Official Video].mp3",
  "Christina Perri - A Thousand Years.mp3",
  "Christina Perri - Jar Of Hearts.mp3",
  "Christina Perry - Burning Gold.mp3",
  "Christina Perry - Human.mp3",
  "Christina Perry - Penguin.mp3",
  "Christina Perry - Sad Song.mp3",
  "Christina Perry - Thousand Years +++.mp3",
  "Christina Perry - Tragedy.mp3",
  "Chrisye - Anak Sekolah.mp3",
  "City of Stars (Duet ft. Ryan Gosling, Emma Stone) - La La Land Original Motion Picture Soundtrack.mp3",
  "Clean Bandit - Symphony feat. Zara Larsson [Official Video].mp3",
  "Close to you.mp3",
  "Coldplay - Everglow (Single Version) - Official video.mp3",
  "Coldplay - Miracles.mp3",
  "Coldplay - True Love.mp3",
  "Come Away With Me-Norah Jones.mp3",
  "Complicated.mp3",
  "Country Roads - JohnDenver.mp3",
  "Crazy.mp3",
  "Céline Dion - A New Day Has Come.mp3",
  "Céline Dion - All By Myself (Official Remastered HD Video) (256 kbps).mp3",
  "Céline Dion - Because You Love Me.mp3",
  "Céline Dion - I'm Alive.mp3",
  "Céline Dion - That's The Way It Is (Upscale 1080p 60fps Enhanced) (256 kbps).mp3",
  "Céline Dion - The Power Of Love (Official Video) (256 kbps).mp3",
  "Céline Dion and R. Kelly - I'm Your Angel (Official Music Video, Studio Version) [1080p] (256 kbps).mp3",
  "DIBATAS KOTA INI.mp3",
  "Dewa 19 - Risalah Hati.mp3",
  "Distance ft Jason Mraz.mp3",
  "Disturbia.mp3",
  "Don't You Remember.mp3",
  "Don't tell me stories - Saskia Serge.mp3",
  "Dua Lipa - New Rules (Official Music Video).mp3",
  "EBIET G ADE = Aku Ingin PuLang.mp3",
  "EBIET G ADE = Titip Rindu Buat Ayah.mp3",
  "EBIET-Berita Kepada .mp3",
  "Ebiet G AD - Elegi Esok Pagi.mp3",
  "Ebiet G AD - Lagu Untuk Sebuah Nama.mp3",
  "Ebiet G Ade - Untuk Kita Renungkan.mp3",
  "Ed Sheeran - Bad Habits.mp3",
  "Ed Sheeran - Bloodstream.mp3",
  "Ed Sheeran - Castle on the Hill.mp3",
  "Ed Sheeran - Dive [Official Audio].mp3",
  "Ed Sheeran - Don't.mp3",
  "Ed Sheeran - How Would You Feel (Paean).mp3",
  "Ed Sheeran - I See Fire.mp3",
  "Ed Sheeran - Nancy Mulligan.mp3",
  "Ed Sheeran - New Man.mp3",
  "Ed Sheeran - Perfect [Official Audio].mp3",
  "Ed Sheeran - Thinking Out Loud (1) (1).mp3",
  "Ellie Goulding - Love Me Like You Do -- Pop.mp3",
  "Ellie Goulding - wemp3.net - On My Mind.mp3",
  "Give Me More Time - Nicole.mp3",
  "Glenn Fredly - Terserah.mp3",
  "Greatest Love Of All.mp3",
  "Gunroses Don'tc~1.mp3",
  "Gunsn Roses Novemb~1.mp3",
  "Hard To Say I'm Sorry.mp3",
  "Heavy (Official Video) - Linkin Park (feat. Kiiara).mp3",
  "Hello.mp3",
  "Hoobastank - Disappear.mp3",
  "Human.mp3",
  "I Gotta Know What's Going On.mp3",
  "I believe.mp3",
  "JANGAN ADA DUSTA DI ANTARA KITA.mp3",
  "Jangan Memilih Aku.mp3",
  "Jasmine_Thompson_-_La_La_La_ft_Sam_Smith_Naughty_Boy_Cover_(cloud-vibe.com).mp3",
  "Jasmine_Thompson_-_Love_The_Way_You_Lie_Rihanna_cover_(cloud-vibe.com).mp3",
  "Jasmine_Thompson_-_Wrecking_Ball_Miley_Cyrus_Cover_(cloud-vibe.com).mp3",
  "Jason Mraz - 3 Things.mp3",
  "Jason Mraz - 93 Million Miles.mp3",
  "Jason Mraz - Bella Luna.mp3",
  "Jason Mraz - Best Friend.mp3",
  "Jason Mraz - Butterfly.mp3",
  "Jason Mraz - I Won't Give Up.mp3",
  "Jason Mraz - I'm Yours.mp3",
  "Jason Mraz - Life Is Wonderful.mp3",
  "Jason Mraz - Lucky (feat. Colbie Caillat) [Official Video].mp3",
  "Jason Mraz - Out of My Hands.mp3",
  "Jason Mraz - The Woman I Love.mp3",
  "Jessie J - Do It Like a Dude.mp3",
  "Jessie J - Domino.mp3",
  "Jessie J - Fire.mp3",
  "Jessie J - Get Away.mp3",
  "Jessie J - Hero.mp3",
  "Jessie J - I Got You (I Feel Good).mp3",
  "Jessie J - Masterpiece.mp3",
  "Jessie J - Nobody's Perfect.mp3",
  "Jessie J - Price Tag.mp3",
  "Jessie J - Sexy Silk.mp3",
  "Jessie J - Sweet Talker.mp3",
  "Jessie J - Thunder.mp3",
  "Jessie J - Who You Are.mp3",
  "Jessie J - Who's Laughing Now.mp3",
  "Jessie-J - Flashlight.mp3",
  "John Denver - Annie Song .mp3",
  "John Lennon - Jealous Guy .mp3",
  "John Lennon - Mother .mp3",
  "John Lennon - Woman  .mp3",
  "John Lenon - Imagine.wav",
  "Judika-Apakah+Ini+Cinta.mp3",
  "Judika_Aku_Yang_Tersakiti.mp3",
  "Judika_Ft_Duma_Sampai_Akhir.mp3",
  "Judika_Mama_Papa_Larang_Mapala.mp3",
  "Justin Bieber - Love Your Self.mp3",
  "Justin Bieber - Sorry.mp3",
  "Justin Timberlake - Can't Stop The Feeling! (Original Song From Dreamworks Animation's _Trolls_).mp3",
  "Justin Timberlake - Cry Me a River.mp3",
  "Justin_Bieber_-_Yummy_(Lyrics)(128k).mp3",
  "KUCARI JALAN TERBAIK.mp3",
  "KUPU-KUPU HITAM PUTIH.mp3",
  "KUPU-KUPU KERTAS.mp3",
  "KUPU-KUPU MALAM.mp3",
  "Katy Perry - Bon Appétit ft. Migos.mp3",
  "Katy Perry - California Girls (feat. Snoop Dogg).mp3",
  "Kotak - Bayang Abadi.mp3",
  "Kotak - Mencintai Ku Dan Dia.mp3",
  "Kotak - Sendiri (Bonys Track).mp3",
  "Kotak - Tetap Ada.mp3",
  "Kotak - Tinggalkan Saja.mp3",
  "Kotak_-_01._Terbang_(New_Version).mp3",
  "Kotak_Kecuali_Kamu.mp3",
  "Kotak_Saat_Kau_Jauh.mp3",
  "Krisdayanti - Cobalah Untuk Setia.mp3",
  "Krisdayanti - Mencintaimu.mp3",
  "Krisdayanti - Yang Kumau.mp3",
  "Krisdayanti feat. Melly Goeslaw - Cinta.mp3",
  "LAGU RINDU.mp3",
  "Last Child - Anak kecil.mp3",
  "Last_Child_-_Tak_Pernah_Ternilai_cover_(_Keesamus_).mp3",
  "Last_Child_Sekuat_Hatimu.mp3",
  "Last_Child_Tak_Pernah_Ternilai.mp3",
  "Last_Shild_Ft_Giselle_Seluruh_Nafas_Ini.mp3",
  "M2M_the day you went.mp3",
  "MAROON 5 this love.mp3",
  "METALLICA - Nothing Else Matters.mp3",
  "METALLICA - The Unforgiven.mp3",
  "Maha Dewi - Risalah Hati.mp3",
  "Mariah Carey - Hero.mp3",
  "Mariah Carey - Without You.mp3",
  "Maroon 5 - Girls Like You.mp3",
  "Maroon 5 - Harder To Breathe.mp3",
  "Maroon 5 - Moves Likes Jagger.MP3",
  "Maroon 5 - She will be loved.mp3",
  "Million Years Ago (Alan Morris Remix).mp3",
  "Mino sayko arigato - Ka-Ka-Ka-Kawai (zaycev.net).mp3",
  "More Than I Can Say.mp3",
  "More Than Words.mp3",
  "Nike Ardilla - Bintang Kehidupan.mp3",
  "Nike Ardilla - Fantasia Bulan Madu (Cinta Kita).mp3",
  "Nike Ardilla - Sandiwara Cinta.mp3",
  "Nike Ardilla - Seberkas Sinar.mp3",
  "Nike Ardilla - Suara Hatiku.mp3",
  "Nike ardila.mp3",
  "Nike_Ardilla - Mama_Aku_Ingin_Pulang.mp3",
  "Nobody But You - Alain Barriebe.mp3",
  "Nobody's Child.mp3",
  "Norah Jones - Chasing Pirates.mp3",
  "Norah Jones - Don't Know Why (320 kbps).mp3",
  "Norah Jones - Nightingale.mp3",
  "Norah Jones - Sunrise (320 kbps).mp3",
  "Norah Jones - Sunrise.mp3",
  "Norah Jones - Those Sweet Words.mp3",
  "Norah Jones - What Am I To You_ (320 kbps).mp3",
  "Norah Jones _ Shoot The Moon.mp3",
  "November Rain - Gun N Roses.mp3",
  "On The Floor New.MP3",
  "One Direction - More Than This.wav",
  "One Direction - Story of My Life-320k.mp3",
  "OneRepublic - 01 - Counting Stars - Copy (2).mp3",
  "PANCE F PONDAAG - Ku Cari Jalan Terbaik.mp3",
  "PERIH.mp3",
  "Pance Kau Telah Berdua.mp3",
  "Passenger_Cover_by_Jasmine_Thompson_-_Let_her_go_cover_(cloud-vibe.com).mp3",
  "Please Forgive Me - Bryan Adams.mp3",
  "Please Release me.mp3",
  "Poppy_Mercury_Surat_Undangan.mp3",
  "Price Tag.mp3",
  "Put Your Head On My Shoulder.mp3",
  "ROSSA - TAK SANGGUP LAGI.mp3",
  "Rap God.mp3",
  "Reflections Of My Life.mp3",
  "Rihanna - Don't Stop The Music.mp3",
  "Rihanna - Farewell.mp3",
  "Rihanna - Fool in Love.mp3",
  "Rihanna - Love The Way You Lie [Eminem ft. Rihanna].mp3",
  "Rihanna - Man Down.mp3",
  "Rihanna - Rihanna - Diamonds.mp3",
  "Rihanna - Roc Me Out.mp3",
  "Rihanna - Russian Roulette.mp3",
  "Rihanna - Umbrella.mp3",
  "Rihanna - Where Have You Been.mp3",
  "Rolling in the deep.mp3",
  "Rossa - Atas Nama Cinta.mp3",
  "Rossa - Hati Yang Kau Sakiti.mp3",
  "Rossa - Ku Menunggu.mp3",
  "Rossa+-+Pudar.mp3",
  "SCOPION - WHITE DOVE.MP3",
  "SCORPION - UNDER THE SAME SUN.MP3",
  "SCORPION - YOU AND  I.MP3",
  "SELURUH NAFAS INI.mp3",
  "SEMPURNA.mp3",
  "Sacrifice - Elton John.mp3",
  "Scorpions (Acoustica) - Holiday.mp3",
  "Scorpions - Always Somewhere.mp3",
  "Scorpions - Still Loving You.mp3",
  "Scorpions Send Me An Angel.mp3",
  "Scorpions_-_Wind_of_Change__ac.mp3",
  "Scorpions_-_You_and_I__acousti.mp3",
  "Set fire to The Rain.mp3",
  "She's Out Of My Life.mp3",
  "Simple Plan - Last One Standing.mp3",
  "Simple Plan - Welcome To My Life.mp3",
  "Simple Plan - You Suck at Love.mp3",
  "Someone Like You.mp3",
  "TAK LEKANG OLEH WAKTU.mp3",
  "TERTATIH.mp3",
  "Tata Janeeta - Penipu Hati.mp3",
  "Taylor Swift - ...Ready For It_  2017 (Pop Stars).mp3",
  "Taylor Swift - Back To December - Copy (2).mp3",
  "Taylor Swift - Bad Blood (feat. Kendrick Lamar).mp3",
  "Taylor Swift - Begin Again - Copy - Copy.mp3",
  "Taylor Swift - Blank Space.mp3",
  "Taylor Swift - Getaway Car 2017 (Pop Stars).mp3",
  "Taylor Swift - I Knew You Were Trouble.mp3",
  "Taylor Swift - Look What You Made Me Do.mp3",
  "Taylor Swift - Love Story.mp3",
  "Taylor Swift - Lover.mp3",
  "Taylor Swift - Shake It Off.mp3",
  "Taylor Swift - Wildest Dreams.mp3",
  "Taylor Swift - You Belong With Me.mp3",
  "Taylor Swift - willow.mp3",
  "Tentang Cinta ( Ipang ) Karaoke.mp3",
  "The Beatles - And I Love Her.mp3",
  "The Beatles - Hey Jude  .mp3",
  "The Beatles - Let It Be.mp3",
  "The Beatles - Yesterday.mp3",
  "The Beatles.mp3",
  "The Chainsmokers - Bloodstream.mp3",
  "The Chainsmokers - Don't Let Me Down (Audio) ft. Daya.mp3",
  "The Chainsmokers The One.mp3",
  "The Lonely.mp3",
  "UNTUK SEBUAH NAMA.mp3",
  "Wake Up Alone(feat. Jhene Aiko).mp3",
  "We Don't Talk Anymore.mp3",
  "Westlife - Flying Without Wings.mp3",
  "Westlife - I Cry.mp3",
  "Westlife - I Do.mp3",
  "Westlife - I Have A Dream.mp3",
  "Westlife - I Lay My Love on You.mp3",
  "Westlife - I Wanna Grow Old With You.mp3",
  "Westlife - If I Let U Go.mp3",
  "Westlife - My Love (acoustic version).mp3",
  "Westlife - Nothing's Gonna Change My Love for You.mp3",
  "Westlife - Soledad.mp3",
  "Westlife - Us Against the World.mp3",
  "Westlife - What About Now.mp3",
  "Westlife - You Raise Me Up.mp3",
  "Westlife_I_Do_1 - Copy - Copy.mp3",
  "What Do You Mean - Justin Bieber (Lyrics).mp3",
  "What Makes You Beautiful.mp3",
  "When A Man Love A Woman.mp3",
  "When I Need You.mp3",
  "When You’re Gone.mp3",
  "White_Lion_You_are_All_I_Need.mp3",
  "Wish You Were Here.mp3",
  "Wiz Khalifa - See You Again (Remix) (Feat. Trey Songz) -- R&B.mp3",
  "Yes You Do - Maureen Kelly.mp3",
  "You Are My Love.mp3",
  "You Are.mp3",
  "You Mean Everything To Me.mp3",
  "You Need Me.mp3",
  "You're My World.mp3",
  "You're Still The One -SHANIA Twain.mp3",
  "You're the inspiration.mp3",
  "Yovie and Nuno - Janji Suci.mp3",
  "Yovie and Nuno - Mengejar Mimpi.mp3",
  "bryan adams - heaven(acoustic).mp3",
  "celine dion - titanic.mp3",
  "christina perry - jar of hearts (alex g cover).mp3",
  "glenn fredly - akhir cerita cinta.mp3",
  "hoobastank - the reason.mp3",
  "ipang - tentang cinta.mp3",
  "my december.mp3",
  "nike_ardilla_-_surat_terakhir.mp3",
  "the reason - hoobastank.mp3",
  "yovie n nuno - sakit hati.mp3",
];
